// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WasmCodeDesc struct {
	Runtime              string   `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Compiler             string   `protobuf:"bytes,2,opt,name=compiler,proto3" json:"compiler,omitempty"`
	Digest               []byte   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	VmCompiler           string   `protobuf:"bytes,4,opt,name=vm_compiler,json=vmCompiler,proto3" json:"vm_compiler,omitempty"`
	ContractType         string   `protobuf:"bytes,5,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasmCodeDesc) Reset()         { *m = WasmCodeDesc{} }
func (m *WasmCodeDesc) String() string { return proto.CompactTextString(m) }
func (*WasmCodeDesc) ProtoMessage()    {}
func (*WasmCodeDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{0}
}

func (m *WasmCodeDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmCodeDesc.Unmarshal(m, b)
}
func (m *WasmCodeDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmCodeDesc.Marshal(b, m, deterministic)
}
func (m *WasmCodeDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmCodeDesc.Merge(m, src)
}
func (m *WasmCodeDesc) XXX_Size() int {
	return xxx_messageInfo_WasmCodeDesc.Size(m)
}
func (m *WasmCodeDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmCodeDesc.DiscardUnknown(m)
}

var xxx_messageInfo_WasmCodeDesc proto.InternalMessageInfo

func (m *WasmCodeDesc) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *WasmCodeDesc) GetCompiler() string {
	if m != nil {
		return m.Compiler
	}
	return ""
}

func (m *WasmCodeDesc) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *WasmCodeDesc) GetVmCompiler() string {
	if m != nil {
		return m.VmCompiler
	}
	return ""
}

func (m *WasmCodeDesc) GetContractType() string {
	if m != nil {
		return m.ContractType
	}
	return ""
}

type ContractEvent struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractEvent) Reset()         { *m = ContractEvent{} }
func (m *ContractEvent) String() string { return proto.CompactTextString(m) }
func (*ContractEvent) ProtoMessage()    {}
func (*ContractEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{1}
}

func (m *ContractEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractEvent.Unmarshal(m, b)
}
func (m *ContractEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractEvent.Marshal(b, m, deterministic)
}
func (m *ContractEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractEvent.Merge(m, src)
}
func (m *ContractEvent) XXX_Size() int {
	return xxx_messageInfo_ContractEvent.Size(m)
}
func (m *ContractEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ContractEvent proto.InternalMessageInfo

func (m *ContractEvent) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ContractEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContractEvent) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*WasmCodeDesc)(nil), "pb.WasmCodeDesc")
	proto.RegisterType((*ContractEvent)(nil), "pb.ContractEvent")
}

func init() { proto.RegisterFile("contract.proto", fileDescriptor_d19debeba7dea55a) }

var fileDescriptor_d19debeba7dea55a = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcd, 0x8a, 0x83, 0x30,
	0x14, 0x85, 0x89, 0xe3, 0x38, 0x33, 0x77, 0x74, 0x16, 0x59, 0x0c, 0xa1, 0x9b, 0x8a, 0xdd, 0xb8,
	0xea, 0xa6, 0x8f, 0x60, 0xfb, 0x02, 0xb6, 0xd0, 0xa5, 0x68, 0xbc, 0x14, 0xa1, 0xf9, 0x21, 0xa6,
	0x82, 0xaf, 0xd3, 0x27, 0x2d, 0x8d, 0x89, 0xbb, 0xf3, 0x9d, 0xe4, 0xc0, 0xc7, 0x85, 0x3f, 0xae,
	0xa4, 0x35, 0x2d, 0xb7, 0x7b, 0x6d, 0x94, 0x55, 0x34, 0xd2, 0x5d, 0xf1, 0x24, 0x90, 0x5e, 0xdb,
	0x51, 0x54, 0xaa, 0xc7, 0x23, 0x8e, 0x9c, 0x32, 0xf8, 0x32, 0x0f, 0x69, 0x07, 0x81, 0x8c, 0xe4,
	0xa4, 0xfc, 0xa9, 0x03, 0xd2, 0x0d, 0x7c, 0x73, 0x25, 0xf4, 0x70, 0x47, 0xc3, 0x22, 0xf7, 0xb4,
	0x32, 0xfd, 0x87, 0xa4, 0x1f, 0x6e, 0x38, 0x5a, 0xf6, 0x91, 0x93, 0x32, 0xad, 0x3d, 0xd1, 0x2d,
	0xfc, 0x4e, 0xa2, 0x59, 0x67, 0xb1, 0x9b, 0xc1, 0x24, 0xaa, 0x30, 0xdc, 0x41, 0x16, 0xac, 0x1a,
	0x3b, 0x6b, 0x64, 0x9f, 0xee, 0x4b, 0x1a, 0xca, 0xcb, 0xac, 0xb1, 0x38, 0x43, 0x56, 0x79, 0x3e,
	0x4d, 0x28, 0xed, 0xa2, 0xb2, 0x14, 0xde, 0x72, 0x65, 0x4a, 0x21, 0x96, 0xad, 0x40, 0xaf, 0xe8,
	0xf2, 0xbb, 0xeb, 0x54, 0x3f, 0x7b, 0x39, 0x97, 0xbb, 0xc4, 0x1d, 0xe1, 0xf0, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x6a, 0x9c, 0xcc, 0xf8, 0x16, 0x01, 0x00, 0x00,
}
