// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type NativeCallRequest struct {
	// The context id of this request
	Ctxid                int64    `protobuf:"varint,1,opt,name=ctxid,proto3" json:"ctxid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NativeCallRequest) Reset()         { *m = NativeCallRequest{} }
func (m *NativeCallRequest) String() string { return proto.CompactTextString(m) }
func (*NativeCallRequest) ProtoMessage()    {}
func (*NativeCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{2}
}

func (m *NativeCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NativeCallRequest.Unmarshal(m, b)
}
func (m *NativeCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NativeCallRequest.Marshal(b, m, deterministic)
}
func (m *NativeCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NativeCallRequest.Merge(m, src)
}
func (m *NativeCallRequest) XXX_Size() int {
	return xxx_messageInfo_NativeCallRequest.Size(m)
}
func (m *NativeCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NativeCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NativeCallRequest proto.InternalMessageInfo

func (m *NativeCallRequest) GetCtxid() int64 {
	if m != nil {
		return m.Ctxid
	}
	return 0
}

type NativeCallResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NativeCallResponse) Reset()         { *m = NativeCallResponse{} }
func (m *NativeCallResponse) String() string { return proto.CompactTextString(m) }
func (*NativeCallResponse) ProtoMessage()    {}
func (*NativeCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{3}
}

func (m *NativeCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NativeCallResponse.Unmarshal(m, b)
}
func (m *NativeCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NativeCallResponse.Marshal(b, m, deterministic)
}
func (m *NativeCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NativeCallResponse.Merge(m, src)
}
func (m *NativeCallResponse) XXX_Size() int {
	return xxx_messageInfo_NativeCallResponse.Size(m)
}
func (m *NativeCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NativeCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NativeCallResponse proto.InternalMessageInfo

type ArgPair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArgPair) Reset()         { *m = ArgPair{} }
func (m *ArgPair) String() string { return proto.CompactTextString(m) }
func (*ArgPair) ProtoMessage()    {}
func (*ArgPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{4}
}

func (m *ArgPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArgPair.Unmarshal(m, b)
}
func (m *ArgPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArgPair.Marshal(b, m, deterministic)
}
func (m *ArgPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArgPair.Merge(m, src)
}
func (m *ArgPair) XXX_Size() int {
	return xxx_messageInfo_ArgPair.Size(m)
}
func (m *ArgPair) XXX_DiscardUnknown() {
	xxx_messageInfo_ArgPair.DiscardUnknown(m)
}

var xxx_messageInfo_ArgPair proto.InternalMessageInfo

func (m *ArgPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ArgPair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type CallArgs struct {
	Method               string     `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Args                 []*ArgPair `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Initiator            string     `protobuf:"bytes,3,opt,name=initiator,proto3" json:"initiator,omitempty"`
	AuthRequire          []string   `protobuf:"bytes,4,rep,name=auth_require,json=authRequire,proto3" json:"auth_require,omitempty"`
	TransferAmount       string     `protobuf:"bytes,5,opt,name=transfer_amount,json=transferAmount,proto3" json:"transfer_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CallArgs) Reset()         { *m = CallArgs{} }
func (m *CallArgs) String() string { return proto.CompactTextString(m) }
func (*CallArgs) ProtoMessage()    {}
func (*CallArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{5}
}

func (m *CallArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallArgs.Unmarshal(m, b)
}
func (m *CallArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallArgs.Marshal(b, m, deterministic)
}
func (m *CallArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallArgs.Merge(m, src)
}
func (m *CallArgs) XXX_Size() int {
	return xxx_messageInfo_CallArgs.Size(m)
}
func (m *CallArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CallArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CallArgs proto.InternalMessageInfo

func (m *CallArgs) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *CallArgs) GetArgs() []*ArgPair {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *CallArgs) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *CallArgs) GetAuthRequire() []string {
	if m != nil {
		return m.AuthRequire
	}
	return nil
}

func (m *CallArgs) GetTransferAmount() string {
	if m != nil {
		return m.TransferAmount
	}
	return ""
}

type SyscallHeader struct {
	Ctxid                int64    `protobuf:"varint,1,opt,name=ctxid,proto3" json:"ctxid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyscallHeader) Reset()         { *m = SyscallHeader{} }
func (m *SyscallHeader) String() string { return proto.CompactTextString(m) }
func (*SyscallHeader) ProtoMessage()    {}
func (*SyscallHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{6}
}

func (m *SyscallHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyscallHeader.Unmarshal(m, b)
}
func (m *SyscallHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyscallHeader.Marshal(b, m, deterministic)
}
func (m *SyscallHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyscallHeader.Merge(m, src)
}
func (m *SyscallHeader) XXX_Size() int {
	return xxx_messageInfo_SyscallHeader.Size(m)
}
func (m *SyscallHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SyscallHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SyscallHeader proto.InternalMessageInfo

func (m *SyscallHeader) GetCtxid() int64 {
	if m != nil {
		return m.Ctxid
	}
	return 0
}

type PutRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Key                  []byte         `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte         `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{7}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{8}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

type GetRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Key                  []byte         `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{9}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{10}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DeleteRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Key                  []byte         `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{11}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{12}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type IteratorRequest struct {
	Header *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// start和limit为[start, limit)
	Start []byte `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Limit []byte `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// cap代表一次请求的最大IteratorItem个数，如果为0则采用xchain的默认配置
	Cap                  int32    `protobuf:"varint,4,opt,name=cap,proto3" json:"cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IteratorRequest) Reset()         { *m = IteratorRequest{} }
func (m *IteratorRequest) String() string { return proto.CompactTextString(m) }
func (*IteratorRequest) ProtoMessage()    {}
func (*IteratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{13}
}

func (m *IteratorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IteratorRequest.Unmarshal(m, b)
}
func (m *IteratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IteratorRequest.Marshal(b, m, deterministic)
}
func (m *IteratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IteratorRequest.Merge(m, src)
}
func (m *IteratorRequest) XXX_Size() int {
	return xxx_messageInfo_IteratorRequest.Size(m)
}
func (m *IteratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IteratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IteratorRequest proto.InternalMessageInfo

func (m *IteratorRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *IteratorRequest) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *IteratorRequest) GetLimit() []byte {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *IteratorRequest) GetCap() int32 {
	if m != nil {
		return m.Cap
	}
	return 0
}

type IteratorItem struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IteratorItem) Reset()         { *m = IteratorItem{} }
func (m *IteratorItem) String() string { return proto.CompactTextString(m) }
func (*IteratorItem) ProtoMessage()    {}
func (*IteratorItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{14}
}

func (m *IteratorItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IteratorItem.Unmarshal(m, b)
}
func (m *IteratorItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IteratorItem.Marshal(b, m, deterministic)
}
func (m *IteratorItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IteratorItem.Merge(m, src)
}
func (m *IteratorItem) XXX_Size() int {
	return xxx_messageInfo_IteratorItem.Size(m)
}
func (m *IteratorItem) XXX_DiscardUnknown() {
	xxx_messageInfo_IteratorItem.DiscardUnknown(m)
}

var xxx_messageInfo_IteratorItem proto.InternalMessageInfo

func (m *IteratorItem) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *IteratorItem) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type IteratorResponse struct {
	Items                []*IteratorItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IteratorResponse) Reset()         { *m = IteratorResponse{} }
func (m *IteratorResponse) String() string { return proto.CompactTextString(m) }
func (*IteratorResponse) ProtoMessage()    {}
func (*IteratorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{15}
}

func (m *IteratorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IteratorResponse.Unmarshal(m, b)
}
func (m *IteratorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IteratorResponse.Marshal(b, m, deterministic)
}
func (m *IteratorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IteratorResponse.Merge(m, src)
}
func (m *IteratorResponse) XXX_Size() int {
	return xxx_messageInfo_IteratorResponse.Size(m)
}
func (m *IteratorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IteratorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IteratorResponse proto.InternalMessageInfo

func (m *IteratorResponse) GetItems() []*IteratorItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type QueryTxRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Txid                 string         `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryTxRequest) Reset()         { *m = QueryTxRequest{} }
func (m *QueryTxRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTxRequest) ProtoMessage()    {}
func (*QueryTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{16}
}

func (m *QueryTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTxRequest.Unmarshal(m, b)
}
func (m *QueryTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTxRequest.Marshal(b, m, deterministic)
}
func (m *QueryTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTxRequest.Merge(m, src)
}
func (m *QueryTxRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTxRequest.Size(m)
}
func (m *QueryTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTxRequest proto.InternalMessageInfo

func (m *QueryTxRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QueryTxRequest) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type QueryTxResponse struct {
	// defined in user code
	Tx                   *Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryTxResponse) Reset()         { *m = QueryTxResponse{} }
func (m *QueryTxResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTxResponse) ProtoMessage()    {}
func (*QueryTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{17}
}

func (m *QueryTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTxResponse.Unmarshal(m, b)
}
func (m *QueryTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTxResponse.Marshal(b, m, deterministic)
}
func (m *QueryTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTxResponse.Merge(m, src)
}
func (m *QueryTxResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTxResponse.Size(m)
}
func (m *QueryTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTxResponse proto.InternalMessageInfo

func (m *QueryTxResponse) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type QueryBlockRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Blockid              string         `protobuf:"bytes,2,opt,name=blockid,proto3" json:"blockid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryBlockRequest) Reset()         { *m = QueryBlockRequest{} }
func (m *QueryBlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBlockRequest) ProtoMessage()    {}
func (*QueryBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{18}
}

func (m *QueryBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBlockRequest.Unmarshal(m, b)
}
func (m *QueryBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBlockRequest.Marshal(b, m, deterministic)
}
func (m *QueryBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBlockRequest.Merge(m, src)
}
func (m *QueryBlockRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBlockRequest.Size(m)
}
func (m *QueryBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBlockRequest proto.InternalMessageInfo

func (m *QueryBlockRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QueryBlockRequest) GetBlockid() string {
	if m != nil {
		return m.Blockid
	}
	return ""
}

type QueryBlockResponse struct {
	// defined in user code
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryBlockResponse) Reset()         { *m = QueryBlockResponse{} }
func (m *QueryBlockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBlockResponse) ProtoMessage()    {}
func (*QueryBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{19}
}

func (m *QueryBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBlockResponse.Unmarshal(m, b)
}
func (m *QueryBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBlockResponse.Marshal(b, m, deterministic)
}
func (m *QueryBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBlockResponse.Merge(m, src)
}
func (m *QueryBlockResponse) XXX_Size() int {
	return xxx_messageInfo_QueryBlockResponse.Size(m)
}
func (m *QueryBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBlockResponse proto.InternalMessageInfo

func (m *QueryBlockResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type TransferRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	From                 string         `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string         `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount               string         `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{20}
}

func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TransferRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransferRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransferRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type TransferResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferResponse) Reset()         { *m = TransferResponse{} }
func (m *TransferResponse) String() string { return proto.CompactTextString(m) }
func (*TransferResponse) ProtoMessage()    {}
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{21}
}

func (m *TransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferResponse.Unmarshal(m, b)
}
func (m *TransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferResponse.Marshal(b, m, deterministic)
}
func (m *TransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferResponse.Merge(m, src)
}
func (m *TransferResponse) XXX_Size() int {
	return xxx_messageInfo_TransferResponse.Size(m)
}
func (m *TransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferResponse proto.InternalMessageInfo

type ContractCallRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Module               string         `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Contract             string         `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Method               string         `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Args                 []*ArgPair     `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ContractCallRequest) Reset()         { *m = ContractCallRequest{} }
func (m *ContractCallRequest) String() string { return proto.CompactTextString(m) }
func (*ContractCallRequest) ProtoMessage()    {}
func (*ContractCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{22}
}

func (m *ContractCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractCallRequest.Unmarshal(m, b)
}
func (m *ContractCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractCallRequest.Marshal(b, m, deterministic)
}
func (m *ContractCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractCallRequest.Merge(m, src)
}
func (m *ContractCallRequest) XXX_Size() int {
	return xxx_messageInfo_ContractCallRequest.Size(m)
}
func (m *ContractCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContractCallRequest proto.InternalMessageInfo

func (m *ContractCallRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ContractCallRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *ContractCallRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ContractCallRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ContractCallRequest) GetArgs() []*ArgPair {
	if m != nil {
		return m.Args
	}
	return nil
}

type ContractCallResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ContractCallResponse) Reset()         { *m = ContractCallResponse{} }
func (m *ContractCallResponse) String() string { return proto.CompactTextString(m) }
func (*ContractCallResponse) ProtoMessage()    {}
func (*ContractCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{23}
}

func (m *ContractCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractCallResponse.Unmarshal(m, b)
}
func (m *ContractCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractCallResponse.Marshal(b, m, deterministic)
}
func (m *ContractCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractCallResponse.Merge(m, src)
}
func (m *ContractCallResponse) XXX_Size() int {
	return xxx_messageInfo_ContractCallResponse.Size(m)
}
func (m *ContractCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContractCallResponse proto.InternalMessageInfo

func (m *ContractCallResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type CrossContractQueryRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Uri                  string         `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Args                 []*ArgPair     `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CrossContractQueryRequest) Reset()         { *m = CrossContractQueryRequest{} }
func (m *CrossContractQueryRequest) String() string { return proto.CompactTextString(m) }
func (*CrossContractQueryRequest) ProtoMessage()    {}
func (*CrossContractQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{24}
}

func (m *CrossContractQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossContractQueryRequest.Unmarshal(m, b)
}
func (m *CrossContractQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossContractQueryRequest.Marshal(b, m, deterministic)
}
func (m *CrossContractQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossContractQueryRequest.Merge(m, src)
}
func (m *CrossContractQueryRequest) XXX_Size() int {
	return xxx_messageInfo_CrossContractQueryRequest.Size(m)
}
func (m *CrossContractQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossContractQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrossContractQueryRequest proto.InternalMessageInfo

func (m *CrossContractQueryRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CrossContractQueryRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *CrossContractQueryRequest) GetArgs() []*ArgPair {
	if m != nil {
		return m.Args
	}
	return nil
}

type CrossContractQueryResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CrossContractQueryResponse) Reset()         { *m = CrossContractQueryResponse{} }
func (m *CrossContractQueryResponse) String() string { return proto.CompactTextString(m) }
func (*CrossContractQueryResponse) ProtoMessage()    {}
func (*CrossContractQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{25}
}

func (m *CrossContractQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossContractQueryResponse.Unmarshal(m, b)
}
func (m *CrossContractQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossContractQueryResponse.Marshal(b, m, deterministic)
}
func (m *CrossContractQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossContractQueryResponse.Merge(m, src)
}
func (m *CrossContractQueryResponse) XXX_Size() int {
	return xxx_messageInfo_CrossContractQueryResponse.Size(m)
}
func (m *CrossContractQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossContractQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrossContractQueryResponse proto.InternalMessageInfo

func (m *CrossContractQueryResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type Response struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{26}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type SetOutputRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Response             *Response      `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetOutputRequest) Reset()         { *m = SetOutputRequest{} }
func (m *SetOutputRequest) String() string { return proto.CompactTextString(m) }
func (*SetOutputRequest) ProtoMessage()    {}
func (*SetOutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{27}
}

func (m *SetOutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOutputRequest.Unmarshal(m, b)
}
func (m *SetOutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOutputRequest.Marshal(b, m, deterministic)
}
func (m *SetOutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOutputRequest.Merge(m, src)
}
func (m *SetOutputRequest) XXX_Size() int {
	return xxx_messageInfo_SetOutputRequest.Size(m)
}
func (m *SetOutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetOutputRequest proto.InternalMessageInfo

func (m *SetOutputRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SetOutputRequest) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type SetOutputResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOutputResponse) Reset()         { *m = SetOutputResponse{} }
func (m *SetOutputResponse) String() string { return proto.CompactTextString(m) }
func (*SetOutputResponse) ProtoMessage()    {}
func (*SetOutputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{28}
}

func (m *SetOutputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOutputResponse.Unmarshal(m, b)
}
func (m *SetOutputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOutputResponse.Marshal(b, m, deterministic)
}
func (m *SetOutputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOutputResponse.Merge(m, src)
}
func (m *SetOutputResponse) XXX_Size() int {
	return xxx_messageInfo_SetOutputResponse.Size(m)
}
func (m *SetOutputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOutputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetOutputResponse proto.InternalMessageInfo

type GetCallArgsRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetCallArgsRequest) Reset()         { *m = GetCallArgsRequest{} }
func (m *GetCallArgsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCallArgsRequest) ProtoMessage()    {}
func (*GetCallArgsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{29}
}

func (m *GetCallArgsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCallArgsRequest.Unmarshal(m, b)
}
func (m *GetCallArgsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCallArgsRequest.Marshal(b, m, deterministic)
}
func (m *GetCallArgsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCallArgsRequest.Merge(m, src)
}
func (m *GetCallArgsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCallArgsRequest.Size(m)
}
func (m *GetCallArgsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCallArgsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCallArgsRequest proto.InternalMessageInfo

func (m *GetCallArgsRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// Transaction input
type TxInput struct {
	// The transaction id referenced to
	RefTxid string `protobuf:"bytes,1,opt,name=ref_txid,json=refTxid,proto3" json:"ref_txid,omitempty"`
	// The output offset of the transaction referenced to
	RefOffset int32 `protobuf:"varint,2,opt,name=ref_offset,json=refOffset,proto3" json:"ref_offset,omitempty"`
	// The address of the launcher
	FromAddr []byte `protobuf:"bytes,5,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	// The amount of the transaction
	Amount string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	// Frozen height
	FrozenHeight         int64    `protobuf:"varint,7,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInput) Reset()         { *m = TxInput{} }
func (m *TxInput) String() string { return proto.CompactTextString(m) }
func (*TxInput) ProtoMessage()    {}
func (*TxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{30}
}

func (m *TxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInput.Unmarshal(m, b)
}
func (m *TxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInput.Marshal(b, m, deterministic)
}
func (m *TxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInput.Merge(m, src)
}
func (m *TxInput) XXX_Size() int {
	return xxx_messageInfo_TxInput.Size(m)
}
func (m *TxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInput.DiscardUnknown(m)
}

var xxx_messageInfo_TxInput proto.InternalMessageInfo

func (m *TxInput) GetRefTxid() string {
	if m != nil {
		return m.RefTxid
	}
	return ""
}

func (m *TxInput) GetRefOffset() int32 {
	if m != nil {
		return m.RefOffset
	}
	return 0
}

func (m *TxInput) GetFromAddr() []byte {
	if m != nil {
		return m.FromAddr
	}
	return nil
}

func (m *TxInput) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TxInput) GetFrozenHeight() int64 {
	if m != nil {
		return m.FrozenHeight
	}
	return 0
}

// Transaction output
type TxOutput struct {
	// The amount of the transaction
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// The address of the launcher
	ToAddr []byte `protobuf:"bytes,2,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	// Fronzen height
	FrozenHeight         int64    `protobuf:"varint,4,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutput) Reset()         { *m = TxOutput{} }
func (m *TxOutput) String() string { return proto.CompactTextString(m) }
func (*TxOutput) ProtoMessage()    {}
func (*TxOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{31}
}

func (m *TxOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutput.Unmarshal(m, b)
}
func (m *TxOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutput.Marshal(b, m, deterministic)
}
func (m *TxOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutput.Merge(m, src)
}
func (m *TxOutput) XXX_Size() int {
	return xxx_messageInfo_TxOutput.Size(m)
}
func (m *TxOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutput proto.InternalMessageInfo

func (m *TxOutput) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TxOutput) GetToAddr() []byte {
	if m != nil {
		return m.ToAddr
	}
	return nil
}

func (m *TxOutput) GetFrozenHeight() int64 {
	if m != nil {
		return m.FrozenHeight
	}
	return 0
}

// Transaction is the information of the transaction
type Transaction struct {
	// txid is the id of this transaction
	Txid string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	// the blockid the transaction belong to
	Blockid string `protobuf:"bytes,2,opt,name=blockid,proto3" json:"blockid,omitempty"`
	// Transaction input list
	TxInputs []*TxInput `protobuf:"bytes,3,rep,name=tx_inputs,json=txInputs,proto3" json:"tx_inputs,omitempty"`
	// Transaction output list
	TxOutputs []*TxOutput `protobuf:"bytes,4,rep,name=tx_outputs,json=txOutputs,proto3" json:"tx_outputs,omitempty"`
	// Transaction description or system contract
	Desc []byte `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	// 权限系统新增字段
	// 交易发起者, 可以是一个Address或者一个Account
	Initiator string `protobuf:"bytes,26,opt,name=initiator,proto3" json:"initiator,omitempty"`
	// 交易发起需要被收集签名的AddressURL集合信息，包括用于utxo转账和用于合约调用
	AuthRequire          []string `protobuf:"bytes,27,rep,name=auth_require,json=authRequire,proto3" json:"auth_require,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{32}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Transaction) GetBlockid() string {
	if m != nil {
		return m.Blockid
	}
	return ""
}

func (m *Transaction) GetTxInputs() []*TxInput {
	if m != nil {
		return m.TxInputs
	}
	return nil
}

func (m *Transaction) GetTxOutputs() []*TxOutput {
	if m != nil {
		return m.TxOutputs
	}
	return nil
}

func (m *Transaction) GetDesc() []byte {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *Transaction) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *Transaction) GetAuthRequire() []string {
	if m != nil {
		return m.AuthRequire
	}
	return nil
}

// The block struct
type Block struct {
	// blockid generate the hash sign of the block used by sha256
	Blockid string `protobuf:"bytes,3,opt,name=blockid,proto3" json:"blockid,omitempty"`
	// pre_hash is the parent blockid of the block
	PreHash string `protobuf:"bytes,4,opt,name=pre_hash,json=preHash,proto3" json:"pre_hash,omitempty"`
	// The miner id
	Proposer []byte `protobuf:"bytes,5,opt,name=proposer,proto3" json:"proposer,omitempty"`
	// The sign which miner signed: blockid + nonce + timestamp
	Sign string `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	// The pk of the miner
	Pubkey []byte `protobuf:"bytes,7,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// The height of the blockchain
	Height int64 `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	// Transactions of the block, only txid stored on kv, the detail information stored in another table
	Txids []string `protobuf:"bytes,11,rep,name=txids,proto3" json:"txids,omitempty"`
	// The transaction count of the block
	TxCount int32 `protobuf:"varint,12,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	//下面的属性会动态变化
	// If the block is on the trunk
	InTrunk bool `protobuf:"varint,14,opt,name=in_trunk,json=inTrunk,proto3" json:"in_trunk,omitempty"`
	// Next next block which on trunk
	NextHash             string   `protobuf:"bytes,15,opt,name=next_hash,json=nextHash,proto3" json:"next_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{33}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBlockid() string {
	if m != nil {
		return m.Blockid
	}
	return ""
}

func (m *Block) GetPreHash() string {
	if m != nil {
		return m.PreHash
	}
	return ""
}

func (m *Block) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *Block) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *Block) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *Block) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetTxids() []string {
	if m != nil {
		return m.Txids
	}
	return nil
}

func (m *Block) GetTxCount() int32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *Block) GetInTrunk() bool {
	if m != nil {
		return m.InTrunk
	}
	return false
}

func (m *Block) GetNextHash() string {
	if m != nil {
		return m.NextHash
	}
	return ""
}

type GetAccountAddressesRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Account              string         `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAccountAddressesRequest) Reset()         { *m = GetAccountAddressesRequest{} }
func (m *GetAccountAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountAddressesRequest) ProtoMessage()    {}
func (*GetAccountAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{34}
}

func (m *GetAccountAddressesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountAddressesRequest.Unmarshal(m, b)
}
func (m *GetAccountAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountAddressesRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountAddressesRequest.Merge(m, src)
}
func (m *GetAccountAddressesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountAddressesRequest.Size(m)
}
func (m *GetAccountAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountAddressesRequest proto.InternalMessageInfo

func (m *GetAccountAddressesRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetAccountAddressesRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type GetAccountAddressesResponse struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountAddressesResponse) Reset()         { *m = GetAccountAddressesResponse{} }
func (m *GetAccountAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountAddressesResponse) ProtoMessage()    {}
func (*GetAccountAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{35}
}

func (m *GetAccountAddressesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountAddressesResponse.Unmarshal(m, b)
}
func (m *GetAccountAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountAddressesResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountAddressesResponse.Merge(m, src)
}
func (m *GetAccountAddressesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountAddressesResponse.Size(m)
}
func (m *GetAccountAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountAddressesResponse proto.InternalMessageInfo

func (m *GetAccountAddressesResponse) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type PostLogRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Entry                string         `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PostLogRequest) Reset()         { *m = PostLogRequest{} }
func (m *PostLogRequest) String() string { return proto.CompactTextString(m) }
func (*PostLogRequest) ProtoMessage()    {}
func (*PostLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{36}
}

func (m *PostLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostLogRequest.Unmarshal(m, b)
}
func (m *PostLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostLogRequest.Marshal(b, m, deterministic)
}
func (m *PostLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostLogRequest.Merge(m, src)
}
func (m *PostLogRequest) XXX_Size() int {
	return xxx_messageInfo_PostLogRequest.Size(m)
}
func (m *PostLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostLogRequest proto.InternalMessageInfo

func (m *PostLogRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PostLogRequest) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

type PostLogResponse struct {
	Entry                string   `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostLogResponse) Reset()         { *m = PostLogResponse{} }
func (m *PostLogResponse) String() string { return proto.CompactTextString(m) }
func (*PostLogResponse) ProtoMessage()    {}
func (*PostLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{37}
}

func (m *PostLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostLogResponse.Unmarshal(m, b)
}
func (m *PostLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostLogResponse.Marshal(b, m, deterministic)
}
func (m *PostLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostLogResponse.Merge(m, src)
}
func (m *PostLogResponse) XXX_Size() int {
	return xxx_messageInfo_PostLogResponse.Size(m)
}
func (m *PostLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostLogResponse proto.InternalMessageInfo

func (m *PostLogResponse) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

type EmitEventRequest struct {
	Header               *SyscallHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Body                 []byte         `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EmitEventRequest) Reset()         { *m = EmitEventRequest{} }
func (m *EmitEventRequest) String() string { return proto.CompactTextString(m) }
func (*EmitEventRequest) ProtoMessage()    {}
func (*EmitEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{38}
}

func (m *EmitEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmitEventRequest.Unmarshal(m, b)
}
func (m *EmitEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmitEventRequest.Marshal(b, m, deterministic)
}
func (m *EmitEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmitEventRequest.Merge(m, src)
}
func (m *EmitEventRequest) XXX_Size() int {
	return xxx_messageInfo_EmitEventRequest.Size(m)
}
func (m *EmitEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmitEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmitEventRequest proto.InternalMessageInfo

func (m *EmitEventRequest) GetHeader() *SyscallHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EmitEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmitEventRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type EmitEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmitEventResponse) Reset()         { *m = EmitEventResponse{} }
func (m *EmitEventResponse) String() string { return proto.CompactTextString(m) }
func (*EmitEventResponse) ProtoMessage()    {}
func (*EmitEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{39}
}

func (m *EmitEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmitEventResponse.Unmarshal(m, b)
}
func (m *EmitEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmitEventResponse.Marshal(b, m, deterministic)
}
func (m *EmitEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmitEventResponse.Merge(m, src)
}
func (m *EmitEventResponse) XXX_Size() int {
	return xxx_messageInfo_EmitEventResponse.Size(m)
}
func (m *EmitEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmitEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmitEventResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingRequest)(nil), "xchain.contract.sdk.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "xchain.contract.sdk.PingResponse")
	proto.RegisterType((*NativeCallRequest)(nil), "xchain.contract.sdk.NativeCallRequest")
	proto.RegisterType((*NativeCallResponse)(nil), "xchain.contract.sdk.NativeCallResponse")
	proto.RegisterType((*ArgPair)(nil), "xchain.contract.sdk.ArgPair")
	proto.RegisterType((*CallArgs)(nil), "xchain.contract.sdk.CallArgs")
	proto.RegisterType((*SyscallHeader)(nil), "xchain.contract.sdk.SyscallHeader")
	proto.RegisterType((*PutRequest)(nil), "xchain.contract.sdk.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "xchain.contract.sdk.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "xchain.contract.sdk.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "xchain.contract.sdk.GetResponse")
	proto.RegisterType((*DeleteRequest)(nil), "xchain.contract.sdk.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "xchain.contract.sdk.DeleteResponse")
	proto.RegisterType((*IteratorRequest)(nil), "xchain.contract.sdk.IteratorRequest")
	proto.RegisterType((*IteratorItem)(nil), "xchain.contract.sdk.IteratorItem")
	proto.RegisterType((*IteratorResponse)(nil), "xchain.contract.sdk.IteratorResponse")
	proto.RegisterType((*QueryTxRequest)(nil), "xchain.contract.sdk.QueryTxRequest")
	proto.RegisterType((*QueryTxResponse)(nil), "xchain.contract.sdk.QueryTxResponse")
	proto.RegisterType((*QueryBlockRequest)(nil), "xchain.contract.sdk.QueryBlockRequest")
	proto.RegisterType((*QueryBlockResponse)(nil), "xchain.contract.sdk.QueryBlockResponse")
	proto.RegisterType((*TransferRequest)(nil), "xchain.contract.sdk.TransferRequest")
	proto.RegisterType((*TransferResponse)(nil), "xchain.contract.sdk.TransferResponse")
	proto.RegisterType((*ContractCallRequest)(nil), "xchain.contract.sdk.ContractCallRequest")
	proto.RegisterType((*ContractCallResponse)(nil), "xchain.contract.sdk.ContractCallResponse")
	proto.RegisterType((*CrossContractQueryRequest)(nil), "xchain.contract.sdk.CrossContractQueryRequest")
	proto.RegisterType((*CrossContractQueryResponse)(nil), "xchain.contract.sdk.CrossContractQueryResponse")
	proto.RegisterType((*Response)(nil), "xchain.contract.sdk.Response")
	proto.RegisterType((*SetOutputRequest)(nil), "xchain.contract.sdk.SetOutputRequest")
	proto.RegisterType((*SetOutputResponse)(nil), "xchain.contract.sdk.SetOutputResponse")
	proto.RegisterType((*GetCallArgsRequest)(nil), "xchain.contract.sdk.GetCallArgsRequest")
	proto.RegisterType((*TxInput)(nil), "xchain.contract.sdk.TxInput")
	proto.RegisterType((*TxOutput)(nil), "xchain.contract.sdk.TxOutput")
	proto.RegisterType((*Transaction)(nil), "xchain.contract.sdk.Transaction")
	proto.RegisterType((*Block)(nil), "xchain.contract.sdk.Block")
	proto.RegisterType((*GetAccountAddressesRequest)(nil), "xchain.contract.sdk.GetAccountAddressesRequest")
	proto.RegisterType((*GetAccountAddressesResponse)(nil), "xchain.contract.sdk.GetAccountAddressesResponse")
	proto.RegisterType((*PostLogRequest)(nil), "xchain.contract.sdk.PostLogRequest")
	proto.RegisterType((*PostLogResponse)(nil), "xchain.contract.sdk.PostLogResponse")
	proto.RegisterType((*EmitEventRequest)(nil), "xchain.contract.sdk.EmitEventRequest")
	proto.RegisterType((*EmitEventResponse)(nil), "xchain.contract.sdk.EmitEventResponse")
}

func init() { proto.RegisterFile("contract.proto", fileDescriptor_d19debeba7dea55a) }

var fileDescriptor_d19debeba7dea55a = []byte{
	// 1235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x06, 0xf5, 0x63, 0x49, 0x23, 0x59, 0xb6, 0x69, 0x23, 0xa5, 0x9d, 0x04, 0x50, 0x18, 0x14,
	0x51, 0x2f, 0x72, 0x9a, 0x02, 0x2d, 0xd2, 0xf6, 0xe2, 0xb8, 0x69, 0x1c, 0xb4, 0x68, 0x1c, 0x46,
	0x40, 0xd1, 0x00, 0x85, 0xb2, 0x22, 0x57, 0xd2, 0xc2, 0x12, 0x97, 0xd9, 0x1d, 0x1a, 0x74, 0xef,
	0x3d, 0x04, 0x7d, 0x84, 0xa2, 0xaf, 0xd2, 0x57, 0xe8, 0x2b, 0x15, 0xfb, 0x43, 0x8a, 0x42, 0xe4,
	0xf4, 0x27, 0xca, 0x6d, 0x66, 0x34, 0x9c, 0xf9, 0xe6, 0x77, 0x47, 0xd0, 0x0d, 0x79, 0x8c, 0x82,
	0x84, 0x38, 0x48, 0x04, 0x47, 0xee, 0xee, 0x67, 0xe1, 0x8c, 0xb0, 0x78, 0x50, 0x88, 0x65, 0x74,
	0xe1, 0x6f, 0x43, 0xfb, 0x9c, 0xc5, 0xd3, 0x80, 0xbe, 0x4e, 0xa9, 0x44, 0xbf, 0x0b, 0x1d, 0xc3,
	0xca, 0x84, 0xc7, 0x92, 0xfa, 0x9f, 0xc0, 0xde, 0x0f, 0x04, 0xd9, 0x25, 0x3d, 0x25, 0xf3, 0xb9,
	0x55, 0x72, 0x0f, 0xa0, 0x1e, 0x62, 0xc6, 0x22, 0xcf, 0xe9, 0x39, 0xfd, 0x6a, 0x60, 0x18, 0xff,
	0x00, 0xdc, 0xb2, 0xaa, 0x35, 0xf0, 0x29, 0x34, 0x4e, 0xc4, 0xf4, 0x9c, 0x30, 0xe1, 0xee, 0x42,
	0xf5, 0x82, 0x5e, 0xe9, 0x8f, 0x5a, 0x81, 0x22, 0x95, 0xa1, 0x4b, 0x32, 0x4f, 0xa9, 0x57, 0xe9,
	0x39, 0xfd, 0x4e, 0x60, 0x18, 0xff, 0x4f, 0x07, 0x9a, 0xca, 0xc6, 0x89, 0x98, 0x4a, 0xf7, 0x06,
	0x6c, 0x2d, 0x28, 0xce, 0x78, 0x64, 0xbf, 0xb3, 0x9c, 0x7b, 0x1f, 0x6a, 0x44, 0x4c, 0xa5, 0x57,
	0xe9, 0x55, 0xfb, 0xed, 0x07, 0xb7, 0x06, 0x6b, 0x62, 0x1b, 0x58, 0xc7, 0x81, 0xd6, 0x74, 0x6f,
	0x41, 0x8b, 0xc5, 0x0c, 0x19, 0x41, 0x2e, 0xbc, 0xaa, 0x36, 0xb6, 0x14, 0xb8, 0x77, 0xa0, 0x43,
	0x52, 0x9c, 0x8d, 0x04, 0x7d, 0x9d, 0x32, 0x41, 0xbd, 0x5a, 0xaf, 0xda, 0x6f, 0x05, 0x6d, 0x25,
	0x0b, 0x8c, 0xc8, 0xbd, 0x07, 0x3b, 0x28, 0x48, 0x2c, 0x27, 0x54, 0x8c, 0xc8, 0x82, 0xa7, 0x31,
	0x7a, 0x75, 0x6d, 0xa6, 0x9b, 0x8b, 0x4f, 0xb4, 0xd4, 0xff, 0x18, 0xb6, 0x5f, 0x5c, 0xc9, 0x90,
	0xcc, 0xe7, 0x67, 0x94, 0x44, 0x54, 0x5c, 0x93, 0xb0, 0x04, 0xe0, 0x3c, 0xc5, 0x3c, 0xa9, 0x5f,
	0xc2, 0xd6, 0x4c, 0x6b, 0x6b, 0xa5, 0xf6, 0x03, 0x7f, 0x6d, 0x48, 0x2b, 0x76, 0x03, 0xfb, 0x45,
	0x9e, 0x59, 0x93, 0xc5, 0xd5, 0xcc, 0x56, 0xcb, 0x99, 0x55, 0xc5, 0x56, 0x1e, 0x6d, 0x6d, 0x5e,
	0x02, 0x3c, 0xa1, 0x1f, 0x06, 0x80, 0x7f, 0x17, 0xda, 0xda, 0xb6, 0x71, 0xb5, 0xc4, 0xe3, 0x94,
	0xf1, 0xfc, 0x0c, 0xdb, 0xdf, 0xd0, 0x39, 0x45, 0xfa, 0x61, 0x30, 0xec, 0x42, 0x37, 0x37, 0x6f,
	0x23, 0xfe, 0xcd, 0x81, 0x9d, 0xa7, 0x48, 0x85, 0x2a, 0xf9, 0x26, 0x7c, 0x1e, 0x40, 0x5d, 0x22,
	0x11, 0x98, 0x37, 0xb0, 0x66, 0x94, 0x74, 0xce, 0x16, 0x0c, 0xf3, 0xe4, 0x6b, 0x46, 0xe1, 0x0b,
	0x49, 0xe2, 0xd5, 0x7a, 0x4e, 0xbf, 0x1e, 0x28, 0xd2, 0xff, 0x1c, 0x3a, 0x39, 0x98, 0xa7, 0x48,
	0x17, 0xe5, 0x01, 0xe9, 0xbc, 0x6b, 0x40, 0xbe, 0x83, 0xdd, 0x65, 0x10, 0x36, 0xc1, 0x5f, 0x40,
	0x9d, 0x21, 0x5d, 0x48, 0xcf, 0xd1, 0x03, 0x71, 0x67, 0x6d, 0x10, 0x65, 0x6f, 0x81, 0xd1, 0xf7,
	0x5f, 0x41, 0xf7, 0x79, 0x4a, 0xc5, 0xd5, 0x30, 0xdb, 0x44, 0x42, 0x5c, 0xa8, 0xe9, 0x46, 0xaf,
	0xe8, 0xc1, 0xd0, 0xb4, 0x7f, 0x0a, 0x3b, 0x85, 0x07, 0x8b, 0xf6, 0x3e, 0x54, 0x30, 0xb3, 0xe6,
	0x7b, 0x6b, 0xcd, 0x0f, 0xd5, 0x48, 0x91, 0x10, 0x19, 0x8f, 0x83, 0x0a, 0x66, 0x3e, 0x83, 0x3d,
	0x6d, 0xe4, 0xd1, 0x9c, 0x87, 0x17, 0x9b, 0x40, 0xea, 0x41, 0x63, 0xac, 0x6c, 0x15, 0x60, 0x73,
	0xd6, 0xff, 0x16, 0xdc, 0xb2, 0xab, 0x02, 0x72, 0x5d, 0x2b, 0x58, 0x57, 0x47, 0x6b, 0x5d, 0x99,
	0x4f, 0x8c, 0xa2, 0xff, 0xc6, 0x81, 0x9d, 0xa1, 0xdd, 0x0c, 0x1b, 0xca, 0xed, 0x44, 0xf0, 0x45,
	0x9e, 0x5b, 0x45, 0xbb, 0x5d, 0xa8, 0x20, 0xb7, 0xdb, 0xac, 0x82, 0x5c, 0xad, 0x4b, 0xbb, 0x9a,
	0x6a, 0x66, 0x5d, 0x1a, 0xce, 0x77, 0x61, 0x77, 0x09, 0xc5, 0x0e, 0xc3, 0x5f, 0x0e, 0xec, 0x9f,
	0x5a, 0xb7, 0xe5, 0xf5, 0xfe, 0x3e, 0x18, 0xd5, 0xba, 0xe6, 0x51, 0x3a, 0xa7, 0x16, 0xa5, 0xe5,
	0xdc, 0x23, 0x68, 0xe6, 0x5f, 0x5b, 0xb4, 0x05, 0x5f, 0x5a, 0xf1, 0xb5, 0xb5, 0x2b, 0xbe, 0xfe,
	0x6f, 0x57, 0xbc, 0xff, 0x1c, 0x0e, 0x56, 0x03, 0xb2, 0xb5, 0x7b, 0x08, 0x4d, 0x61, 0x69, 0x1b,
	0xd3, 0xed, 0xb5, 0xd6, 0xf2, 0x0f, 0x82, 0x42, 0xdd, 0xff, 0xdd, 0x81, 0xc3, 0x53, 0xc1, 0xa5,
	0xcc, 0x0d, 0xeb, 0xd6, 0xd8, 0xd0, 0xbe, 0x4a, 0x05, 0xb3, 0x79, 0x52, 0xe4, 0xff, 0x08, 0xf8,
	0x47, 0x38, 0x5a, 0x07, 0xee, 0xfd, 0xc3, 0x3e, 0x87, 0x66, 0x61, 0xe6, 0x06, 0x6c, 0x49, 0x24,
	0x98, 0x4a, 0x6d, 0xa4, 0x1e, 0x58, 0x4e, 0x4d, 0xd0, 0x82, 0x4a, 0x49, 0xa6, 0x79, 0xb1, 0x73,
	0x56, 0x75, 0xea, 0x98, 0x47, 0x57, 0x76, 0xff, 0x69, 0x5a, 0x4d, 0xc3, 0xee, 0x0b, 0x8a, 0xcf,
	0x52, 0x4c, 0x36, 0xf3, 0xe8, 0x95, 0xa3, 0xab, 0xfc, 0xb7, 0xe8, 0xf6, 0x61, 0xaf, 0x04, 0xa5,
	0x08, 0xd9, 0x7d, 0x42, 0x31, 0x3f, 0x3c, 0x36, 0x80, 0xd0, 0xff, 0xc3, 0x81, 0xc6, 0x30, 0x7b,
	0x1a, 0x27, 0x29, 0xba, 0x87, 0x0a, 0xed, 0x64, 0x54, 0x5c, 0x01, 0xad, 0xa0, 0x21, 0xe8, 0x64,
	0x98, 0xb1, 0xc8, 0xbd, 0x0d, 0xa0, 0x7e, 0xe2, 0x93, 0x89, 0xa4, 0xe6, 0x25, 0xa9, 0x07, 0x2d,
	0x41, 0x27, 0xcf, 0xb4, 0xc0, 0xbd, 0x09, 0x2d, 0x35, 0xea, 0x23, 0x12, 0x45, 0x42, 0x1f, 0x1c,
	0x9d, 0xa0, 0xa9, 0x04, 0x27, 0x51, 0x24, 0x4a, 0xf3, 0xbe, 0x55, 0x9e, 0x77, 0xf7, 0x2e, 0x6c,
	0x4f, 0x04, 0xff, 0x85, 0xc6, 0xa3, 0x19, 0x65, 0xd3, 0x19, 0x7a, 0x0d, 0x7d, 0x79, 0x74, 0x8c,
	0xf0, 0x4c, 0xcb, 0xfc, 0x57, 0xd0, 0x1c, 0x66, 0x26, 0x0b, 0x25, 0x43, 0xce, 0x8a, 0xa1, 0x8f,
	0xa0, 0x81, 0xdc, 0xf8, 0x36, 0x6f, 0xd0, 0x16, 0x72, 0xed, 0xf9, 0x2d, 0x0f, 0xb5, 0x35, 0x1e,
	0xde, 0x54, 0xa0, 0x5d, 0xda, 0xe4, 0xc5, 0xf3, 0xe0, 0x2c, 0x9f, 0x87, 0xeb, 0x17, 0xb1, 0xfb,
	0x10, 0x5a, 0x98, 0x8d, 0x98, 0xca, 0x9f, 0xf4, 0xaa, 0xef, 0x18, 0x0a, 0x9b, 0xe4, 0xa0, 0x89,
	0x86, 0x90, 0xee, 0xd7, 0x00, 0x98, 0x8d, 0xb8, 0x8e, 0x4d, 0xea, 0x63, 0xee, 0xba, 0xf6, 0xc8,
	0x33, 0x10, 0xb4, 0xd0, 0x52, 0x52, 0xc1, 0x8c, 0xa8, 0x0c, 0x75, 0x4e, 0x3b, 0x81, 0xa6, 0x57,
	0xcf, 0xc7, 0xa3, 0x7f, 0x3a, 0x1f, 0x6f, 0xbe, 0x75, 0x3e, 0xfa, 0xbf, 0x56, 0xa0, 0xae, 0xdf,
	0x87, 0x72, 0xc4, 0xd5, 0xd5, 0x88, 0x0f, 0xa1, 0x99, 0x08, 0x3a, 0x9a, 0x11, 0x39, 0xb3, 0xcb,
	0xb0, 0x91, 0x08, 0x7a, 0x46, 0xe4, 0x4c, 0x6d, 0xd0, 0x44, 0xf0, 0x84, 0x4b, 0x5a, 0x74, 0x41,
	0xce, 0x2b, 0xbc, 0x92, 0x4d, 0x63, 0xdb, 0x03, 0x9a, 0x56, 0x05, 0x4d, 0xd2, 0xb1, 0xba, 0x27,
	0x1a, 0xa6, 0x6e, 0x86, 0x53, 0x72, 0x5b, 0xb0, 0x96, 0x2e, 0x98, 0xe5, 0xd4, 0xa9, 0xa1, 0xca,
	0x21, 0xbd, 0xb6, 0x86, 0x6e, 0x18, 0x05, 0x08, 0xb3, 0x51, 0xa8, 0x1b, 0xa3, 0xa3, 0x3b, 0xb3,
	0x81, 0xd9, 0xa9, 0xee, 0x8c, 0x43, 0x68, 0xb2, 0x78, 0x84, 0x22, 0x8d, 0x2f, 0xbc, 0x6e, 0xcf,
	0xe9, 0x37, 0x83, 0x06, 0x8b, 0x87, 0x8a, 0x55, 0x2d, 0x1b, 0xd3, 0x0c, 0x4d, 0x1c, 0x3b, 0x66,
	0xdd, 0x2b, 0x81, 0x0a, 0xc4, 0x17, 0x70, 0xf4, 0x84, 0xe2, 0x49, 0xa8, 0x8d, 0xaa, 0x56, 0xa2,
	0x52, 0x52, 0xb9, 0xa1, 0x27, 0x9d, 0x18, 0xb3, 0x79, 0x27, 0x59, 0xd6, 0xff, 0x0a, 0x6e, 0xae,
	0xf5, 0x69, 0x37, 0xdc, 0x2d, 0x68, 0x91, 0x5c, 0xa8, 0x0f, 0xa8, 0x56, 0xb0, 0x14, 0xf8, 0x63,
	0xe8, 0x9e, 0x73, 0x89, 0xdf, 0xf3, 0xe9, 0x86, 0x4e, 0x46, 0x1a, 0xa3, 0xb8, 0xb2, 0x10, 0x0d,
	0xe3, 0xdf, 0x83, 0x9d, 0xc2, 0xc7, 0xf2, 0x64, 0x36, 0x8a, 0x4e, 0x59, 0xf1, 0x12, 0x76, 0x1f,
	0x2f, 0x18, 0x3e, 0xbe, 0xa4, 0x31, 0x6e, 0xe8, 0xa8, 0x88, 0xc9, 0x22, 0xdf, 0xe0, 0x9a, 0x5e,
	0xbb, 0xbe, 0xf7, 0x61, 0xaf, 0xe4, 0xd7, 0x40, 0x7c, 0xf4, 0x13, 0x1c, 0x85, 0x7c, 0x31, 0x18,
	0x13, 0x16, 0xa5, 0x83, 0x2c, 0x4d, 0xa8, 0x28, 0x5c, 0x26, 0xe3, 0xb3, 0xea, 0xcb, 0x87, 0x53,
	0x86, 0xb3, 0x74, 0x3c, 0x08, 0xf9, 0xe2, 0x58, 0xff, 0xac, 0x61, 0x59, 0x92, 0x0b, 0x7a, 0x7c,
	0x41, 0x45, 0x4c, 0xe7, 0xc7, 0xf9, 0x47, 0xc7, 0x63, 0xc1, 0xa2, 0x29, 0x3d, 0x4e, 0xc6, 0xe3,
	0x2d, 0xfd, 0x9f, 0xf5, 0xb3, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x75, 0x55, 0x36, 0x94, 0xc5,
	0x0e, 0x00, 0x00,
}
