coverage:
  precision: 2
  round: down
  range: "30...80"
  status:
    project:
      default:
        target: 45%
        threshold: 0%
        branches: 
          - master
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  behavior: new
  require_changes: false
  branches:               
    - "master"

