// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xchain.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type XchainErrNo int32

const (
	XchainErrNo_SUCCESS XchainErrNo = 0
	// 内部错误
	XchainErrNo_INTERNAL_ERROR XchainErrNo = 1
	// 参数错误
	XchainErrNo_PARAM_ERROR XchainErrNo = 2
	// 未知错误
	XchainErrNo_UNKNOW_ERROR XchainErrNo = 3
)

var XchainErrNo_name = map[int32]string{
	0: "SUCCESS",
	1: "INTERNAL_ERROR",
	2: "PARAM_ERROR",
	3: "UNKNOW_ERROR",
}

var XchainErrNo_value = map[string]int32{
	"SUCCESS":        0,
	"INTERNAL_ERROR": 1,
	"PARAM_ERROR":    2,
	"UNKNOW_ERROR":   3,
}

func (x XchainErrNo) String() string {
	return proto.EnumName(XchainErrNo_name, int32(x))
}

func (XchainErrNo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db0991b9525664ca, []int{0}
}

// 通用请求Header
type ReqHeader struct {
	// 请求id
	LogId string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 标记请求方，方便问题定位
	SelfName             string   `protobuf:"bytes,2,opt,name=self_name,json=selfName,proto3" json:"self_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHeader) Reset()         { *m = ReqHeader{} }
func (m *ReqHeader) String() string { return proto.CompactTextString(m) }
func (*ReqHeader) ProtoMessage()    {}
func (*ReqHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_db0991b9525664ca, []int{0}
}

func (m *ReqHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHeader.Unmarshal(m, b)
}
func (m *ReqHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHeader.Marshal(b, m, deterministic)
}
func (m *ReqHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHeader.Merge(m, src)
}
func (m *ReqHeader) XXX_Size() int {
	return xxx_messageInfo_ReqHeader.Size(m)
}
func (m *ReqHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHeader proto.InternalMessageInfo

func (m *ReqHeader) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *ReqHeader) GetSelfName() string {
	if m != nil {
		return m.SelfName
	}
	return ""
}

// 通用响应Header
type RespHeader struct {
	// 请求id
	LogId string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 错误码
	Error XchainErrNo `protobuf:"varint,2,opt,name=error,proto3,enum=pb.XchainErrNo" json:"error,omitempty"`
	// 节点追踪信息，方便问题定位
	TraceId              string   `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespHeader) Reset()         { *m = RespHeader{} }
func (m *RespHeader) String() string { return proto.CompactTextString(m) }
func (*RespHeader) ProtoMessage()    {}
func (*RespHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_db0991b9525664ca, []int{1}
}

func (m *RespHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespHeader.Unmarshal(m, b)
}
func (m *RespHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespHeader.Marshal(b, m, deterministic)
}
func (m *RespHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespHeader.Merge(m, src)
}
func (m *RespHeader) XXX_Size() int {
	return xxx_messageInfo_RespHeader.Size(m)
}
func (m *RespHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RespHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RespHeader proto.InternalMessageInfo

func (m *RespHeader) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

func (m *RespHeader) GetError() XchainErrNo {
	if m != nil {
		return m.Error
	}
	return XchainErrNo_SUCCESS
}

func (m *RespHeader) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type BaseReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BaseReq) Reset()         { *m = BaseReq{} }
func (m *BaseReq) String() string { return proto.CompactTextString(m) }
func (*BaseReq) ProtoMessage()    {}
func (*BaseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db0991b9525664ca, []int{2}
}

func (m *BaseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReq.Unmarshal(m, b)
}
func (m *BaseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReq.Marshal(b, m, deterministic)
}
func (m *BaseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReq.Merge(m, src)
}
func (m *BaseReq) XXX_Size() int {
	return xxx_messageInfo_BaseReq.Size(m)
}
func (m *BaseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReq.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReq proto.InternalMessageInfo

func (m *BaseReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type BaseResp struct {
	Header               *RespHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BaseResp) Reset()         { *m = BaseResp{} }
func (m *BaseResp) String() string { return proto.CompactTextString(m) }
func (*BaseResp) ProtoMessage()    {}
func (*BaseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db0991b9525664ca, []int{3}
}

func (m *BaseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResp.Unmarshal(m, b)
}
func (m *BaseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResp.Marshal(b, m, deterministic)
}
func (m *BaseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResp.Merge(m, src)
}
func (m *BaseResp) XXX_Size() int {
	return xxx_messageInfo_BaseResp.Size(m)
}
func (m *BaseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResp.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResp proto.InternalMessageInfo

func (m *BaseResp) GetHeader() *RespHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.XchainErrNo", XchainErrNo_name, XchainErrNo_value)
	proto.RegisterType((*ReqHeader)(nil), "pb.ReqHeader")
	proto.RegisterType((*RespHeader)(nil), "pb.RespHeader")
	proto.RegisterType((*BaseReq)(nil), "pb.BaseReq")
	proto.RegisterType((*BaseResp)(nil), "pb.BaseResp")
}

func init() { proto.RegisterFile("xchain.proto", fileDescriptor_db0991b9525664ca) }

var fileDescriptor_db0991b9525664ca = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xfb, 0x87, 0xa6, 0xed, 0xa4, 0xb6, 0x65, 0x40, 0xa8, 0x7a, 0x91, 0x40, 0x45, 0x3d,
	0x14, 0x49, 0x3f, 0x80, 0xc4, 0x12, 0xb0, 0xa8, 0x5b, 0xdd, 0x5a, 0xf4, 0x16, 0x36, 0xc9, 0xd8,
	0x06, 0xd3, 0xee, 0x76, 0x53, 0xc4, 0x8f, 0x2f, 0xd9, 0xa4, 0x2a, 0x1e, 0x3c, 0xce, 0x7b, 0xfc,
	0xde, 0xbc, 0x61, 0xa0, 0xf3, 0x19, 0xad, 0x44, 0xb2, 0x19, 0x29, 0x2d, 0x77, 0x12, 0x6b, 0x2a,
	0x74, 0xae, 0xa1, 0xcd, 0x69, 0x7b, 0x4b, 0x22, 0x26, 0x8d, 0x87, 0x60, 0xa5, 0x72, 0x19, 0x24,
	0xf1, 0xa0, 0x7a, 0x5a, 0x3d, 0x6f, 0xf3, 0x46, 0x2a, 0x97, 0xd3, 0x18, 0x4f, 0xa0, 0x9d, 0x51,
	0xfa, 0x16, 0x6c, 0xc4, 0x9a, 0x06, 0x35, 0xe3, 0xb4, 0x72, 0x81, 0x89, 0x35, 0x39, 0x04, 0xc0,
	0x29, 0x53, 0xff, 0x27, 0x0c, 0xa1, 0x41, 0x5a, 0x4b, 0x6d, 0xe8, 0xae, 0xdb, 0x1b, 0xa9, 0x70,
	0xf4, 0x6a, 0xaa, 0xf8, 0x5a, 0x33, 0xc9, 0x0b, 0x17, 0x8f, 0xa0, 0xb5, 0xd3, 0x22, 0xa2, 0x9c,
	0xaf, 0x1b, 0xbe, 0x69, 0xe6, 0x69, 0xec, 0x5c, 0x41, 0xf3, 0x46, 0x64, 0xc4, 0x69, 0x8b, 0x43,
	0xb0, 0x8a, 0x6d, 0x66, 0x87, 0xed, 0x1e, 0xe4, 0x69, 0xdf, 0x47, 0xf0, 0xd2, 0x74, 0x5c, 0x68,
	0x15, 0x44, 0xa6, 0xf0, 0xec, 0x0f, 0xd2, 0x2d, 0x90, 0x7d, 0xed, 0x3d, 0x73, 0xf9, 0x04, 0xf6,
	0xaf, 0x5a, 0x68, 0x43, 0x73, 0xbe, 0x98, 0x4c, 0xfc, 0xf9, 0xbc, 0x5f, 0x41, 0x84, 0xee, 0x94,
	0x3d, 0xfb, 0x9c, 0x79, 0xf7, 0x81, 0xcf, 0xf9, 0x8c, 0xf7, 0xab, 0xd8, 0x03, 0xfb, 0xd1, 0xe3,
	0xde, 0x43, 0x29, 0xd4, 0xb0, 0x0f, 0x9d, 0x05, 0xbb, 0x63, 0xb3, 0x97, 0x52, 0xa9, 0xbb, 0x63,
	0xb0, 0x8a, 0x48, 0xbc, 0x00, 0x98, 0xac, 0x28, 0x7a, 0xf7, 0xd2, 0xe4, 0x83, 0xd0, 0xce, 0x2b,
	0x94, 0x27, 0x1d, 0x77, 0x7e, 0x86, 0x4c, 0x39, 0x95, 0xd0, 0x32, 0x0f, 0x1a, 0x7f, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xe0, 0xa9, 0x7a, 0x5e, 0xb0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// XchainClient is the client API for Xchain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XchainClient interface {
	// 示例接口
	CheckAlive(ctx context.Context, in *BaseReq, opts ...grpc.CallOption) (*BaseResp, error)
}

type xchainClient struct {
	cc grpc.ClientConnInterface
}

func NewXchainClient(cc grpc.ClientConnInterface) XchainClient {
	return &xchainClient{cc}
}

func (c *xchainClient) CheckAlive(ctx context.Context, in *BaseReq, opts ...grpc.CallOption) (*BaseResp, error) {
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, "/pb.Xchain/CheckAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XchainServer is the server API for Xchain service.
type XchainServer interface {
	// 示例接口
	CheckAlive(context.Context, *BaseReq) (*BaseResp, error)
}

// UnimplementedXchainServer can be embedded to have forward compatible implementations.
type UnimplementedXchainServer struct {
}

func (*UnimplementedXchainServer) CheckAlive(ctx context.Context, req *BaseReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAlive not implemented")
}

func RegisterXchainServer(s *grpc.Server, srv XchainServer) {
	s.RegisterService(&_Xchain_serviceDesc, srv)
}

func _Xchain_CheckAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XchainServer).CheckAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Xchain/CheckAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XchainServer).CheckAlive(ctx, req.(*BaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Xchain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Xchain",
	HandlerType: (*XchainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAlive",
			Handler:    _Xchain_CheckAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xchain.proto",
}
