// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bls.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 交换公钥请求
type BroadcastPublicKeyRequest struct {
	// 编号
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// 公钥
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// 组：成员P2P ID
	Group                []string `protobuf:"bytes,3,rep,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastPublicKeyRequest) Reset()         { *m = BroadcastPublicKeyRequest{} }
func (m *BroadcastPublicKeyRequest) String() string { return proto.CompactTextString(m) }
func (*BroadcastPublicKeyRequest) ProtoMessage()    {}
func (*BroadcastPublicKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8cbd3bd749373c5, []int{0}
}

func (m *BroadcastPublicKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastPublicKeyRequest.Unmarshal(m, b)
}
func (m *BroadcastPublicKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastPublicKeyRequest.Marshal(b, m, deterministic)
}
func (m *BroadcastPublicKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastPublicKeyRequest.Merge(m, src)
}
func (m *BroadcastPublicKeyRequest) XXX_Size() int {
	return xxx_messageInfo_BroadcastPublicKeyRequest.Size(m)
}
func (m *BroadcastPublicKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastPublicKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastPublicKeyRequest proto.InternalMessageInfo

func (m *BroadcastPublicKeyRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *BroadcastPublicKeyRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *BroadcastPublicKeyRequest) GetGroup() []string {
	if m != nil {
		return m.Group
	}
	return nil
}

// 交换公钥响应
type BroadcastPublicKeyResponse struct {
	// 成功标志
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（如果发生错误）
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 错误代码
	ErrorCode int32 `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// 编号
	Index string `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	// 公钥
	PublicKey            []byte   `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastPublicKeyResponse) Reset()         { *m = BroadcastPublicKeyResponse{} }
func (m *BroadcastPublicKeyResponse) String() string { return proto.CompactTextString(m) }
func (*BroadcastPublicKeyResponse) ProtoMessage()    {}
func (*BroadcastPublicKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8cbd3bd749373c5, []int{1}
}

func (m *BroadcastPublicKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastPublicKeyResponse.Unmarshal(m, b)
}
func (m *BroadcastPublicKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastPublicKeyResponse.Marshal(b, m, deterministic)
}
func (m *BroadcastPublicKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastPublicKeyResponse.Merge(m, src)
}
func (m *BroadcastPublicKeyResponse) XXX_Size() int {
	return xxx_messageInfo_BroadcastPublicKeyResponse.Size(m)
}
func (m *BroadcastPublicKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastPublicKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastPublicKeyResponse proto.InternalMessageInfo

func (m *BroadcastPublicKeyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BroadcastPublicKeyResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *BroadcastPublicKeyResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *BroadcastPublicKeyResponse) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *BroadcastPublicKeyResponse) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

// 交换成员签名碎片请求
type SendMemberSignRequest struct {
	// 编号
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// 签名碎片
	MemberSign           []byte   `protobuf:"bytes,2,opt,name=member_sign,json=memberSign,proto3" json:"member_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMemberSignRequest) Reset()         { *m = SendMemberSignRequest{} }
func (m *SendMemberSignRequest) String() string { return proto.CompactTextString(m) }
func (*SendMemberSignRequest) ProtoMessage()    {}
func (*SendMemberSignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8cbd3bd749373c5, []int{2}
}

func (m *SendMemberSignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMemberSignRequest.Unmarshal(m, b)
}
func (m *SendMemberSignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMemberSignRequest.Marshal(b, m, deterministic)
}
func (m *SendMemberSignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMemberSignRequest.Merge(m, src)
}
func (m *SendMemberSignRequest) XXX_Size() int {
	return xxx_messageInfo_SendMemberSignRequest.Size(m)
}
func (m *SendMemberSignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMemberSignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMemberSignRequest proto.InternalMessageInfo

func (m *SendMemberSignRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *SendMemberSignRequest) GetMemberSign() []byte {
	if m != nil {
		return m.MemberSign
	}
	return nil
}

// 交换成员签名碎片响应
type SendMemberSignResponse struct {
	// 成功标志
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（如果发生错误）
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 错误代码
	ErrorCode int32 `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// 编号
	Index string `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	// 签名碎片
	MemberSign           []byte   `protobuf:"bytes,5,opt,name=member_sign,json=memberSign,proto3" json:"member_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMemberSignResponse) Reset()         { *m = SendMemberSignResponse{} }
func (m *SendMemberSignResponse) String() string { return proto.CompactTextString(m) }
func (*SendMemberSignResponse) ProtoMessage()    {}
func (*SendMemberSignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8cbd3bd749373c5, []int{3}
}

func (m *SendMemberSignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMemberSignResponse.Unmarshal(m, b)
}
func (m *SendMemberSignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMemberSignResponse.Marshal(b, m, deterministic)
}
func (m *SendMemberSignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMemberSignResponse.Merge(m, src)
}
func (m *SendMemberSignResponse) XXX_Size() int {
	return xxx_messageInfo_SendMemberSignResponse.Size(m)
}
func (m *SendMemberSignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMemberSignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMemberSignResponse proto.InternalMessageInfo

func (m *SendMemberSignResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SendMemberSignResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *SendMemberSignResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *SendMemberSignResponse) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *SendMemberSignResponse) GetMemberSign() []byte {
	if m != nil {
		return m.MemberSign
	}
	return nil
}

// 交换消息签名碎片请求
type BroadcastMessageSignRequest struct {
	// 编号
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// 消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 签名碎片
	MessageSign []byte `protobuf:"bytes,3,opt,name=message_sign,json=messageSign,proto3" json:"message_sign,omitempty"`
	// 高度
	Height               uint64   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastMessageSignRequest) Reset()         { *m = BroadcastMessageSignRequest{} }
func (m *BroadcastMessageSignRequest) String() string { return proto.CompactTextString(m) }
func (*BroadcastMessageSignRequest) ProtoMessage()    {}
func (*BroadcastMessageSignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8cbd3bd749373c5, []int{4}
}

func (m *BroadcastMessageSignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastMessageSignRequest.Unmarshal(m, b)
}
func (m *BroadcastMessageSignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastMessageSignRequest.Marshal(b, m, deterministic)
}
func (m *BroadcastMessageSignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastMessageSignRequest.Merge(m, src)
}
func (m *BroadcastMessageSignRequest) XXX_Size() int {
	return xxx_messageInfo_BroadcastMessageSignRequest.Size(m)
}
func (m *BroadcastMessageSignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastMessageSignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastMessageSignRequest proto.InternalMessageInfo

func (m *BroadcastMessageSignRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *BroadcastMessageSignRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BroadcastMessageSignRequest) GetMessageSign() []byte {
	if m != nil {
		return m.MessageSign
	}
	return nil
}

func (m *BroadcastMessageSignRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// 交换消息签名碎片响应
type BroadcastMessageSignResponse struct {
	// 成功标志
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（如果发生错误）
	ErrorMessage []byte `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 错误代码
	ErrorCode int32 `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// 编号
	Index string `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	// 消息
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// 签名碎片
	MessageSign []byte `protobuf:"bytes,6,opt,name=message_sign,json=messageSign,proto3" json:"message_sign,omitempty"`
	// 高度
	Height               uint64   `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastMessageSignResponse) Reset()         { *m = BroadcastMessageSignResponse{} }
func (m *BroadcastMessageSignResponse) String() string { return proto.CompactTextString(m) }
func (*BroadcastMessageSignResponse) ProtoMessage()    {}
func (*BroadcastMessageSignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8cbd3bd749373c5, []int{5}
}

func (m *BroadcastMessageSignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastMessageSignResponse.Unmarshal(m, b)
}
func (m *BroadcastMessageSignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastMessageSignResponse.Marshal(b, m, deterministic)
}
func (m *BroadcastMessageSignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastMessageSignResponse.Merge(m, src)
}
func (m *BroadcastMessageSignResponse) XXX_Size() int {
	return xxx_messageInfo_BroadcastMessageSignResponse.Size(m)
}
func (m *BroadcastMessageSignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastMessageSignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastMessageSignResponse proto.InternalMessageInfo

func (m *BroadcastMessageSignResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BroadcastMessageSignResponse) GetErrorMessage() []byte {
	if m != nil {
		return m.ErrorMessage
	}
	return nil
}

func (m *BroadcastMessageSignResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *BroadcastMessageSignResponse) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *BroadcastMessageSignResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BroadcastMessageSignResponse) GetMessageSign() []byte {
	if m != nil {
		return m.MessageSign
	}
	return nil
}

func (m *BroadcastMessageSignResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*BroadcastPublicKeyRequest)(nil), "pb.BroadcastPublicKeyRequest")
	proto.RegisterType((*BroadcastPublicKeyResponse)(nil), "pb.BroadcastPublicKeyResponse")
	proto.RegisterType((*SendMemberSignRequest)(nil), "pb.SendMemberSignRequest")
	proto.RegisterType((*SendMemberSignResponse)(nil), "pb.SendMemberSignResponse")
	proto.RegisterType((*BroadcastMessageSignRequest)(nil), "pb.BroadcastMessageSignRequest")
	proto.RegisterType((*BroadcastMessageSignResponse)(nil), "pb.BroadcastMessageSignResponse")
}

func init() { proto.RegisterFile("bls.proto", fileDescriptor_c8cbd3bd749373c5) }

var fileDescriptor_c8cbd3bd749373c5 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xcd, 0x6e, 0x9b, 0x40,
	0x10, 0xee, 0x1a, 0x63, 0x97, 0x31, 0xed, 0x61, 0xe5, 0x5a, 0x98, 0xd6, 0x35, 0xa5, 0x17, 0x9f,
	0x7c, 0x68, 0xdf, 0x20, 0x39, 0x45, 0x91, 0xa3, 0x08, 0x2b, 0xa7, 0x1c, 0x2c, 0x03, 0x13, 0x8c,
	0x62, 0x58, 0xc2, 0x82, 0x14, 0xdf, 0x73, 0xc8, 0xcb, 0x44, 0x79, 0xac, 0xbc, 0x46, 0xc4, 0x02,
	0xfe, 0x05, 0x47, 0x8a, 0x22, 0xe5, 0xc6, 0xcc, 0xce, 0xcc, 0xf7, 0xb3, 0xb3, 0x80, 0x62, 0x2f,
	0xf9, 0x38, 0x8a, 0x59, 0xc2, 0x68, 0x23, 0xb2, 0xcd, 0x1b, 0xe8, 0x9f, 0xc4, 0x6c, 0xee, 0x3a,
	0x73, 0x9e, 0x5c, 0xa6, 0xf6, 0xd2, 0x77, 0xce, 0x71, 0x65, 0xe1, 0x5d, 0x8a, 0x3c, 0xa1, 0x5d,
	0x90, 0xfd, 0xd0, 0xc5, 0x7b, 0x8d, 0x18, 0x64, 0xa4, 0x58, 0x79, 0x40, 0x07, 0x00, 0x91, 0xa8,
	0x9c, 0xdd, 0xe2, 0x4a, 0x6b, 0x18, 0x64, 0xa4, 0x5a, 0x4a, 0x54, 0xf6, 0x66, 0x4d, 0x5e, 0xcc,
	0xd2, 0x48, 0x93, 0x0c, 0x29, 0x6b, 0x12, 0x81, 0xf9, 0x4c, 0x40, 0xaf, 0x02, 0xe2, 0x11, 0x0b,
	0x39, 0x52, 0x0d, 0xda, 0x3c, 0x75, 0x1c, 0xe4, 0x5c, 0x60, 0x7d, 0xb5, 0xca, 0x90, 0xfe, 0x85,
	0x6f, 0x18, 0xc7, 0x2c, 0x9e, 0x05, 0xc8, 0xf9, 0xdc, 0x43, 0x01, 0xa8, 0x58, 0xaa, 0x48, 0x4e,
	0xf2, 0x5c, 0x46, 0x29, 0x2f, 0x72, 0x98, 0x8b, 0x9a, 0x64, 0x90, 0x91, 0x6c, 0x29, 0x22, 0x73,
	0xca, 0x5c, 0xdc, 0xe8, 0x68, 0xd6, 0xeb, 0x90, 0xf7, 0x74, 0x98, 0x17, 0xf0, 0x63, 0x8a, 0xa1,
	0x3b, 0xc1, 0xc0, 0xc6, 0x78, 0xea, 0x7b, 0xe1, 0x71, 0x57, 0x86, 0xd0, 0x09, 0x44, 0xe9, 0x8c,
	0xfb, 0x5e, 0x58, 0xd8, 0x02, 0xc1, 0xba, 0xdb, 0x7c, 0x22, 0xd0, 0xdb, 0x1f, 0xf8, 0x89, 0xea,
	0xf7, 0xf8, 0xca, 0x07, 0x7c, 0x1f, 0x09, 0xfc, 0x5c, 0xdf, 0x58, 0x01, 0xf5, 0xb6, 0x0d, 0x1a,
	0xb4, 0x77, 0xa9, 0x96, 0x21, 0xfd, 0x03, 0x6a, 0xf1, 0x99, 0x23, 0x4a, 0x02, 0xb1, 0x13, 0x6c,
	0x26, 0xd3, 0x1e, 0xb4, 0x16, 0xe8, 0x7b, 0x8b, 0x44, 0x50, 0x6d, 0x5a, 0x45, 0x64, 0xbe, 0x10,
	0xf8, 0x55, 0x4d, 0xe5, 0x7d, 0x06, 0xaa, 0x1f, 0x61, 0xe0, 0x96, 0x52, 0xf9, 0xb8, 0xd2, 0xd6,
	0x31, 0xa5, 0xed, 0x6d, 0xa5, 0xff, 0x1e, 0x1a, 0x20, 0xd9, 0x4b, 0x4e, 0xaf, 0x80, 0x1e, 0xbe,
	0x16, 0x3a, 0x18, 0x47, 0xf6, 0xb8, 0xf6, 0xb9, 0xea, 0xbf, 0xeb, 0x8e, 0x73, 0x97, 0xcc, 0x2f,
	0xf4, 0x0c, 0xbe, 0xef, 0xae, 0x20, 0xed, 0x67, 0x3d, 0x95, 0x7b, 0xae, 0xeb, 0x55, 0x47, 0xeb,
	0x51, 0xd7, 0xd0, 0xad, 0xba, 0x12, 0x3a, 0xdc, 0x21, 0x71, 0xb8, 0x37, 0xba, 0x51, 0x5f, 0x50,
	0x0e, 0xb7, 0x5b, 0xe2, 0x07, 0xf5, 0xff, 0x35, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xe8, 0x41, 0xc7,
	0xad, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BlsClient is the client API for Bls service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlsClient interface {
	// 交换公钥
	BroadcastPublicKey(ctx context.Context, in *BroadcastPublicKeyRequest, opts ...grpc.CallOption) (*BroadcastPublicKeyResponse, error)
	// 交换成员签名碎片
	SendMemberSign(ctx context.Context, in *SendMemberSignRequest, opts ...grpc.CallOption) (*SendMemberSignResponse, error)
	// 交换消息签名碎片
	BroadcastMessageSign(ctx context.Context, in *BroadcastMessageSignRequest, opts ...grpc.CallOption) (*BroadcastMessageSignResponse, error)
}

type blsClient struct {
	cc grpc.ClientConnInterface
}

func NewBlsClient(cc grpc.ClientConnInterface) BlsClient {
	return &blsClient{cc}
}

func (c *blsClient) BroadcastPublicKey(ctx context.Context, in *BroadcastPublicKeyRequest, opts ...grpc.CallOption) (*BroadcastPublicKeyResponse, error) {
	out := new(BroadcastPublicKeyResponse)
	err := c.cc.Invoke(ctx, "/pb.bls/BroadcastPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blsClient) SendMemberSign(ctx context.Context, in *SendMemberSignRequest, opts ...grpc.CallOption) (*SendMemberSignResponse, error) {
	out := new(SendMemberSignResponse)
	err := c.cc.Invoke(ctx, "/pb.bls/SendMemberSign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blsClient) BroadcastMessageSign(ctx context.Context, in *BroadcastMessageSignRequest, opts ...grpc.CallOption) (*BroadcastMessageSignResponse, error) {
	out := new(BroadcastMessageSignResponse)
	err := c.cc.Invoke(ctx, "/pb.bls/BroadcastMessageSign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlsServer is the server API for Bls service.
type BlsServer interface {
	// 交换公钥
	BroadcastPublicKey(context.Context, *BroadcastPublicKeyRequest) (*BroadcastPublicKeyResponse, error)
	// 交换成员签名碎片
	SendMemberSign(context.Context, *SendMemberSignRequest) (*SendMemberSignResponse, error)
	// 交换消息签名碎片
	BroadcastMessageSign(context.Context, *BroadcastMessageSignRequest) (*BroadcastMessageSignResponse, error)
}

// UnimplementedBlsServer can be embedded to have forward compatible implementations.
type UnimplementedBlsServer struct {
}

func (*UnimplementedBlsServer) BroadcastPublicKey(ctx context.Context, req *BroadcastPublicKeyRequest) (*BroadcastPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastPublicKey not implemented")
}
func (*UnimplementedBlsServer) SendMemberSign(ctx context.Context, req *SendMemberSignRequest) (*SendMemberSignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMemberSign not implemented")
}
func (*UnimplementedBlsServer) BroadcastMessageSign(ctx context.Context, req *BroadcastMessageSignRequest) (*BroadcastMessageSignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastMessageSign not implemented")
}

func RegisterBlsServer(s *grpc.Server, srv BlsServer) {
	s.RegisterService(&_Bls_serviceDesc, srv)
}

func _Bls_BroadcastPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlsServer).BroadcastPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.bls/BroadcastPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlsServer).BroadcastPublicKey(ctx, req.(*BroadcastPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bls_SendMemberSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMemberSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlsServer).SendMemberSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.bls/SendMemberSign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlsServer).SendMemberSign(ctx, req.(*SendMemberSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bls_BroadcastMessageSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastMessageSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlsServer).BroadcastMessageSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.bls/BroadcastMessageSign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlsServer).BroadcastMessageSign(ctx, req.(*BroadcastMessageSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bls_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.bls",
	HandlerType: (*BlsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastPublicKey",
			Handler:    _Bls_BroadcastPublicKey_Handler,
		},
		{
			MethodName: "SendMemberSign",
			Handler:    _Bls_SendMemberSign_Handler,
		},
		{
			MethodName: "BroadcastMessageSign",
			Handler:    _Bls_BroadcastMessageSign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bls.proto",
}
