// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourceType int32

const (
	ResourceType_CPU    ResourceType = 0
	ResourceType_MEMORY ResourceType = 1
	ResourceType_DISK   ResourceType = 2
	// the fee used in kernel contract
	ResourceType_XFEE ResourceType = 3
)

var ResourceType_name = map[int32]string{
	0: "CPU",
	1: "MEMORY",
	2: "DISK",
	3: "XFEE",
}

var ResourceType_value = map[string]int32{
	"CPU":    0,
	"MEMORY": 1,
	"DISK":   2,
	"XFEE":   3,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}

func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{0}
}

type GasPrice struct {
	CpuRate              int64    `protobuf:"varint,1,opt,name=cpu_rate,json=cpuRate,proto3" json:"cpu_rate,omitempty"`
	MemRate              int64    `protobuf:"varint,2,opt,name=mem_rate,json=memRate,proto3" json:"mem_rate,omitempty"`
	DiskRate             int64    `protobuf:"varint,3,opt,name=disk_rate,json=diskRate,proto3" json:"disk_rate,omitempty"`
	XfeeRate             int64    `protobuf:"varint,4,opt,name=xfee_rate,json=xfeeRate,proto3" json:"xfee_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GasPrice) Reset()         { *m = GasPrice{} }
func (m *GasPrice) String() string { return proto.CompactTextString(m) }
func (*GasPrice) ProtoMessage()    {}
func (*GasPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{0}
}

func (m *GasPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasPrice.Unmarshal(m, b)
}
func (m *GasPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasPrice.Marshal(b, m, deterministic)
}
func (m *GasPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasPrice.Merge(m, src)
}
func (m *GasPrice) XXX_Size() int {
	return xxx_messageInfo_GasPrice.Size(m)
}
func (m *GasPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_GasPrice.DiscardUnknown(m)
}

var xxx_messageInfo_GasPrice proto.InternalMessageInfo

func (m *GasPrice) GetCpuRate() int64 {
	if m != nil {
		return m.CpuRate
	}
	return 0
}

func (m *GasPrice) GetMemRate() int64 {
	if m != nil {
		return m.MemRate
	}
	return 0
}

func (m *GasPrice) GetDiskRate() int64 {
	if m != nil {
		return m.DiskRate
	}
	return 0
}

func (m *GasPrice) GetXfeeRate() int64 {
	if m != nil {
		return m.XfeeRate
	}
	return 0
}

type ResourceLimit struct {
	Type                 ResourceType `protobuf:"varint,1,opt,name=type,proto3,enum=protos.ResourceType" json:"type,omitempty"`
	Limit                int64        `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResourceLimit) Reset()         { *m = ResourceLimit{} }
func (m *ResourceLimit) String() string { return proto.CompactTextString(m) }
func (*ResourceLimit) ProtoMessage()    {}
func (*ResourceLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{1}
}

func (m *ResourceLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceLimit.Unmarshal(m, b)
}
func (m *ResourceLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceLimit.Marshal(b, m, deterministic)
}
func (m *ResourceLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceLimit.Merge(m, src)
}
func (m *ResourceLimit) XXX_Size() int {
	return xxx_messageInfo_ResourceLimit.Size(m)
}
func (m *ResourceLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceLimit.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceLimit proto.InternalMessageInfo

func (m *ResourceLimit) GetType() ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceType_CPU
}

func (m *ResourceLimit) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// 预执行的请求结构
type InvokeRequest struct {
	ModuleName     string            `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	ContractName   string            `protobuf:"bytes,2,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	MethodName     string            `protobuf:"bytes,3,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Args           map[string][]byte `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ResourceLimits []*ResourceLimit  `protobuf:"bytes,5,rep,name=resource_limits,json=resourceLimits,proto3" json:"resource_limits,omitempty"`
	// amount is the amount transfer to the contract
	// attention: In one transaction, transfer to only one contract is allowed
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeRequest) Reset()         { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()    {}
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{2}
}

func (m *InvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeRequest.Unmarshal(m, b)
}
func (m *InvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeRequest.Marshal(b, m, deterministic)
}
func (m *InvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeRequest.Merge(m, src)
}
func (m *InvokeRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeRequest.Size(m)
}
func (m *InvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeRequest proto.InternalMessageInfo

func (m *InvokeRequest) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *InvokeRequest) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *InvokeRequest) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *InvokeRequest) GetArgs() map[string][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *InvokeRequest) GetResourceLimits() []*ResourceLimit {
	if m != nil {
		return m.ResourceLimits
	}
	return nil
}

func (m *InvokeRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// 预执行的返回结构
type InvokeResponse struct {
	Inputs               []*TxInputExt       `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*TxOutputExt      `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Response             [][]byte            `protobuf:"bytes,3,rep,name=response,proto3" json:"response,omitempty"`
	GasUsed              int64               `protobuf:"varint,4,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Requests             []*InvokeRequest    `protobuf:"bytes,5,rep,name=requests,proto3" json:"requests,omitempty"`
	Responses            []*ContractResponse `protobuf:"bytes,6,rep,name=responses,proto3" json:"responses,omitempty"`
	UtxoInputs           []*TxInput          `protobuf:"bytes,7,rep,name=utxoInputs,proto3" json:"utxoInputs,omitempty"`
	UtxoOutputs          []*TxOutput         `protobuf:"bytes,8,rep,name=utxoOutputs,proto3" json:"utxoOutputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InvokeResponse) Reset()         { *m = InvokeResponse{} }
func (m *InvokeResponse) String() string { return proto.CompactTextString(m) }
func (*InvokeResponse) ProtoMessage()    {}
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{3}
}

func (m *InvokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeResponse.Unmarshal(m, b)
}
func (m *InvokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeResponse.Marshal(b, m, deterministic)
}
func (m *InvokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeResponse.Merge(m, src)
}
func (m *InvokeResponse) XXX_Size() int {
	return xxx_messageInfo_InvokeResponse.Size(m)
}
func (m *InvokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeResponse proto.InternalMessageInfo

func (m *InvokeResponse) GetInputs() []*TxInputExt {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *InvokeResponse) GetOutputs() []*TxOutputExt {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *InvokeResponse) GetResponse() [][]byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *InvokeResponse) GetGasUsed() int64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *InvokeResponse) GetRequests() []*InvokeRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *InvokeResponse) GetResponses() []*ContractResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *InvokeResponse) GetUtxoInputs() []*TxInput {
	if m != nil {
		return m.UtxoInputs
	}
	return nil
}

func (m *InvokeResponse) GetUtxoOutputs() []*TxOutput {
	if m != nil {
		return m.UtxoOutputs
	}
	return nil
}

// ContractResponse is the response returnd by contract
type ContractResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractResponse) Reset()         { *m = ContractResponse{} }
func (m *ContractResponse) String() string { return proto.CompactTextString(m) }
func (*ContractResponse) ProtoMessage()    {}
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{4}
}

func (m *ContractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractResponse.Unmarshal(m, b)
}
func (m *ContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractResponse.Marshal(b, m, deterministic)
}
func (m *ContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractResponse.Merge(m, src)
}
func (m *ContractResponse) XXX_Size() int {
	return xxx_messageInfo_ContractResponse.Size(m)
}
func (m *ContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContractResponse proto.InternalMessageInfo

func (m *ContractResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ContractResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ContractResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type WasmCodeDesc struct {
	Runtime              string   `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Compiler             string   `protobuf:"bytes,2,opt,name=compiler,proto3" json:"compiler,omitempty"`
	Digest               []byte   `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	VmCompiler           string   `protobuf:"bytes,4,opt,name=vm_compiler,json=vmCompiler,proto3" json:"vm_compiler,omitempty"`
	ContractType         string   `protobuf:"bytes,5,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WasmCodeDesc) Reset()         { *m = WasmCodeDesc{} }
func (m *WasmCodeDesc) String() string { return proto.CompactTextString(m) }
func (*WasmCodeDesc) ProtoMessage()    {}
func (*WasmCodeDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{5}
}

func (m *WasmCodeDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WasmCodeDesc.Unmarshal(m, b)
}
func (m *WasmCodeDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WasmCodeDesc.Marshal(b, m, deterministic)
}
func (m *WasmCodeDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WasmCodeDesc.Merge(m, src)
}
func (m *WasmCodeDesc) XXX_Size() int {
	return xxx_messageInfo_WasmCodeDesc.Size(m)
}
func (m *WasmCodeDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_WasmCodeDesc.DiscardUnknown(m)
}

var xxx_messageInfo_WasmCodeDesc proto.InternalMessageInfo

func (m *WasmCodeDesc) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *WasmCodeDesc) GetCompiler() string {
	if m != nil {
		return m.Compiler
	}
	return ""
}

func (m *WasmCodeDesc) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *WasmCodeDesc) GetVmCompiler() string {
	if m != nil {
		return m.VmCompiler
	}
	return ""
}

func (m *WasmCodeDesc) GetContractType() string {
	if m != nil {
		return m.ContractType
	}
	return ""
}

type ContractEvent struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractEvent) Reset()         { *m = ContractEvent{} }
func (m *ContractEvent) String() string { return proto.CompactTextString(m) }
func (*ContractEvent) ProtoMessage()    {}
func (*ContractEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{6}
}

func (m *ContractEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractEvent.Unmarshal(m, b)
}
func (m *ContractEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractEvent.Marshal(b, m, deterministic)
}
func (m *ContractEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractEvent.Merge(m, src)
}
func (m *ContractEvent) XXX_Size() int {
	return xxx_messageInfo_ContractEvent.Size(m)
}
func (m *ContractEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ContractEvent proto.InternalMessageInfo

func (m *ContractEvent) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ContractEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContractEvent) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ContractStatData struct {
	AccountCount         int64    `protobuf:"varint,1,opt,name=accountCount,proto3" json:"accountCount,omitempty"`
	ContractCount        int64    `protobuf:"varint,2,opt,name=contractCount,proto3" json:"contractCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractStatData) Reset()         { *m = ContractStatData{} }
func (m *ContractStatData) String() string { return proto.CompactTextString(m) }
func (*ContractStatData) ProtoMessage()    {}
func (*ContractStatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{7}
}

func (m *ContractStatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractStatData.Unmarshal(m, b)
}
func (m *ContractStatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractStatData.Marshal(b, m, deterministic)
}
func (m *ContractStatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractStatData.Merge(m, src)
}
func (m *ContractStatData) XXX_Size() int {
	return xxx_messageInfo_ContractStatData.Size(m)
}
func (m *ContractStatData) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractStatData.DiscardUnknown(m)
}

var xxx_messageInfo_ContractStatData proto.InternalMessageInfo

func (m *ContractStatData) GetAccountCount() int64 {
	if m != nil {
		return m.AccountCount
	}
	return 0
}

func (m *ContractStatData) GetContractCount() int64 {
	if m != nil {
		return m.ContractCount
	}
	return 0
}

// Status of a contract
type ContractStatus struct {
	ContractName         string   `protobuf:"bytes,1,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	Txid                 string   `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	Desc                 []byte   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	IsBanned             bool     `protobuf:"varint,4,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Runtime              string   `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractStatus) Reset()         { *m = ContractStatus{} }
func (m *ContractStatus) String() string { return proto.CompactTextString(m) }
func (*ContractStatus) ProtoMessage()    {}
func (*ContractStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{8}
}

func (m *ContractStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractStatus.Unmarshal(m, b)
}
func (m *ContractStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractStatus.Marshal(b, m, deterministic)
}
func (m *ContractStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractStatus.Merge(m, src)
}
func (m *ContractStatus) XXX_Size() int {
	return xxx_messageInfo_ContractStatus.Size(m)
}
func (m *ContractStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ContractStatus proto.InternalMessageInfo

func (m *ContractStatus) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ContractStatus) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *ContractStatus) GetDesc() []byte {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *ContractStatus) GetIsBanned() bool {
	if m != nil {
		return m.IsBanned
	}
	return false
}

func (m *ContractStatus) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ContractStatus) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func init() {
	proto.RegisterEnum("protos.ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterType((*GasPrice)(nil), "protos.GasPrice")
	proto.RegisterType((*ResourceLimit)(nil), "protos.ResourceLimit")
	proto.RegisterType((*InvokeRequest)(nil), "protos.InvokeRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "protos.InvokeRequest.ArgsEntry")
	proto.RegisterType((*InvokeResponse)(nil), "protos.InvokeResponse")
	proto.RegisterType((*ContractResponse)(nil), "protos.ContractResponse")
	proto.RegisterType((*WasmCodeDesc)(nil), "protos.WasmCodeDesc")
	proto.RegisterType((*ContractEvent)(nil), "protos.ContractEvent")
	proto.RegisterType((*ContractStatData)(nil), "protos.ContractStatData")
	proto.RegisterType((*ContractStatus)(nil), "protos.ContractStatus")
}

func init() { proto.RegisterFile("contract.proto", fileDescriptor_d19debeba7dea55a) }

var fileDescriptor_d19debeba7dea55a = []byte{
	// 811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x55, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0x26, 0xb1, 0x9b, 0x38, 0x53, 0x37, 0x17, 0x2d, 0x07, 0x32, 0x05, 0xe9, 0x2a, 0x83, 0x50,
	0x74, 0x12, 0xad, 0xe8, 0x49, 0x1c, 0xe2, 0x03, 0x12, 0x97, 0x06, 0x54, 0xc1, 0xd1, 0xd3, 0xf6,
	0x4e, 0x1c, 0x08, 0x29, 0xda, 0xda, 0x8b, 0x6b, 0x35, 0xeb, 0x35, 0xfb, 0x12, 0x25, 0xfc, 0x1c,
	0x7e, 0x02, 0x9f, 0xf9, 0x55, 0xfc, 0x02, 0xb4, 0x6f, 0x89, 0xd3, 0xeb, 0xa7, 0xec, 0x33, 0xf3,
	0xcc, 0xf8, 0x99, 0x99, 0x9d, 0x0d, 0x8c, 0x0b, 0xde, 0x28, 0x41, 0x0a, 0x75, 0xda, 0x0a, 0xae,
	0x38, 0x1a, 0xd8, 0x1f, 0x79, 0x9c, 0x2e, 0x69, 0x59, 0x51, 0xe1, 0xac, 0xf9, 0x5f, 0x90, 0xfc,
	0x40, 0xe4, 0x2b, 0x51, 0x17, 0x14, 0x7d, 0x04, 0x49, 0xd1, 0xea, 0x85, 0x20, 0x8a, 0x66, 0xbd,
	0x93, 0xde, 0x34, 0xc2, 0xc3, 0xa2, 0xd5, 0x98, 0x28, 0xeb, 0x62, 0x94, 0x39, 0x57, 0xdf, 0xb9,
	0x18, 0x65, 0xd6, 0xf5, 0x31, 0x8c, 0xca, 0x5a, 0xde, 0x39, 0x5f, 0x64, 0x7d, 0x89, 0x31, 0x04,
	0xe7, 0xfa, 0x0f, 0x4a, 0x9d, 0x33, 0x76, 0x4e, 0x63, 0x30, 0xce, 0xfc, 0x0a, 0x8e, 0x30, 0x95,
	0x5c, 0x8b, 0x82, 0xfe, 0x54, 0xb3, 0x5a, 0xa1, 0x29, 0xc4, 0x6a, 0xd3, 0xba, 0x8f, 0x8f, 0xcf,
	0x1f, 0x3b, 0x89, 0xf2, 0x34, 0x90, 0x5e, 0x6f, 0x5a, 0x8a, 0x2d, 0x03, 0x3d, 0x86, 0x83, 0xa5,
	0x09, 0xf1, 0x62, 0x1c, 0xc8, 0xff, 0xed, 0xc3, 0xd1, 0x65, 0xb3, 0xe2, 0x77, 0x14, 0xd3, 0x3f,
	0x35, 0x95, 0x0a, 0x3d, 0x81, 0x43, 0xc6, 0x4b, 0xbd, 0xa4, 0x8b, 0x86, 0x30, 0x97, 0x78, 0x84,
	0xc1, 0x99, 0x7e, 0x26, 0x8c, 0xa2, 0x4f, 0xe1, 0x28, 0xf4, 0xc9, 0x51, 0xfa, 0x96, 0x92, 0x06,
	0xa3, 0x25, 0x99, 0x2c, 0x54, 0xdd, 0xf2, 0xd2, 0x51, 0x22, 0x9f, 0xc5, 0x9a, 0x2c, 0xe1, 0x19,
	0xc4, 0x44, 0x54, 0x32, 0x8b, 0x4f, 0xa2, 0xe9, 0xe1, 0xf9, 0x93, 0x20, 0x7c, 0x4f, 0xcb, 0xe9,
	0x77, 0xa2, 0x92, 0xf3, 0x46, 0x89, 0x0d, 0xb6, 0x64, 0xf4, 0x2d, 0x3c, 0x12, 0xbe, 0xb2, 0x85,
	0xd5, 0x2f, 0xb3, 0x03, 0x1b, 0xff, 0xc1, 0xfd, 0xc2, 0x6d, 0x77, 0xf0, 0x58, 0x74, 0xa1, 0x44,
	0x1f, 0xc2, 0x80, 0x30, 0xae, 0x1b, 0x95, 0x0d, 0xac, 0x20, 0x8f, 0x8e, 0x9f, 0xc3, 0x68, 0xfb,
	0x29, 0x34, 0x81, 0xe8, 0x8e, 0x6e, 0x7c, 0xe1, 0xe6, 0x68, 0x5a, 0xb7, 0x22, 0x4b, 0xed, 0x2a,
	0x4d, 0xb1, 0x03, 0xdf, 0xf4, 0xbf, 0xee, 0xe5, 0xff, 0xf5, 0x61, 0x1c, 0x24, 0xcb, 0x96, 0x37,
	0x92, 0xa2, 0xa7, 0x30, 0xa8, 0x9b, 0x56, 0x2b, 0x99, 0xf5, 0xac, 0x34, 0x14, 0xa4, 0xbd, 0x5e,
	0x5f, 0x1a, 0xfb, 0x7c, 0xad, 0xb0, 0x67, 0xa0, 0x2f, 0x60, 0xc8, 0xb5, 0xb2, 0xe4, 0xbe, 0x25,
	0xbf, 0xbf, 0x23, 0x5f, 0x59, 0x87, 0x61, 0x07, 0x0e, 0x3a, 0x86, 0x44, 0xf8, 0xcf, 0x64, 0xd1,
	0x49, 0x34, 0x4d, 0xf1, 0x16, 0x9b, 0xeb, 0x56, 0x11, 0xb9, 0xd0, 0x92, 0x96, 0xfe, 0xd6, 0x0c,
	0x2b, 0x22, 0xdf, 0x48, 0x5a, 0xa2, 0x2f, 0x4d, 0x98, 0x6d, 0xe8, 0x3b, 0xed, 0xda, 0x6b, 0x37,
	0xde, 0xd2, 0xd0, 0x57, 0x30, 0x0a, 0x99, 0x65, 0x36, 0xb0, 0x31, 0x59, 0x88, 0x99, 0xf9, 0x39,
	0x87, 0x8a, 0xf1, 0x8e, 0x8a, 0xce, 0x00, 0xb4, 0x5a, 0xf3, 0x4b, 0xd7, 0x80, 0xa1, 0x0d, 0x7c,
	0x74, 0xaf, 0x01, 0xb8, 0x43, 0x41, 0xe7, 0x70, 0x68, 0xd0, 0x95, 0xef, 0x42, 0x62, 0x23, 0x26,
	0xf7, 0xbb, 0x80, 0xbb, 0xa4, 0xfc, 0x2d, 0x4c, 0xee, 0x6b, 0x30, 0x93, 0x95, 0x8a, 0x28, 0x2d,
	0xed, 0xdc, 0x0e, 0xb0, 0x47, 0x28, 0x83, 0x21, 0xa3, 0x52, 0x92, 0x2a, 0x5c, 0xd3, 0x00, 0x11,
	0x82, 0xf8, 0x86, 0x97, 0x1b, 0x7b, 0x35, 0x53, 0x6c, 0xcf, 0xf9, 0xdf, 0x3d, 0x48, 0x7f, 0x21,
	0x92, 0xcd, 0x78, 0x49, 0x2f, 0xa8, 0x2c, 0x4c, 0xb8, 0xd0, 0x8d, 0xaa, 0xb7, 0x8b, 0x10, 0xa0,
	0x99, 0x45, 0xc1, 0x59, 0x5b, 0x2f, 0xa9, 0xf0, 0x99, 0xb7, 0xd8, 0x88, 0x29, 0xeb, 0x8a, 0x4a,
	0xe5, 0x93, 0x7b, 0x64, 0x96, 0x62, 0xc5, 0x16, 0xdb, 0xb0, 0xd8, 0x2d, 0xc5, 0x8a, 0xcd, 0x42,
	0x60, 0x77, 0xb5, 0xec, 0x5a, 0x1f, 0xec, 0xaf, 0x96, 0x59, 0xe7, 0xfc, 0x1a, 0x8e, 0x42, 0xf9,
	0xf3, 0x15, 0x6d, 0x94, 0x93, 0xe2, 0x0c, 0x5e, 0xe5, 0x16, 0x9b, 0x2a, 0x3b, 0x3b, 0x6a, 0xcf,
	0x0f, 0x56, 0xfe, 0xfb, 0xae, 0xa7, 0xd7, 0x8a, 0xa8, 0x0b, 0xa2, 0x08, 0xca, 0x21, 0x25, 0x45,
	0x61, 0x16, 0x64, 0x66, 0x77, 0xc6, 0x3d, 0x70, 0x7b, 0x36, 0xf4, 0xd9, 0x4e, 0xb1, 0x23, 0xb9,
	0xd7, 0x65, 0xdf, 0x98, 0xff, 0xd3, 0x83, 0x71, 0x37, 0xbd, 0x96, 0xef, 0xbe, 0x22, 0xbd, 0x07,
	0x5e, 0x11, 0x04, 0xb1, 0x5a, 0xd7, 0x65, 0x50, 0x6f, 0xce, 0xc6, 0x56, 0x52, 0x59, 0x04, 0xf5,
	0xe6, 0x6c, 0xde, 0xcc, 0x5a, 0x2e, 0x6e, 0x48, 0xd3, 0xf8, 0xdb, 0x9f, 0xe0, 0xa4, 0x96, 0x2f,
	0x2c, 0x46, 0x9f, 0xc0, 0xc8, 0x4c, 0x4c, 0x2a, 0xc2, 0x5a, 0xdb, 0xd0, 0x08, 0xef, 0x0c, 0xdd,
	0x09, 0x0f, 0xf6, 0x26, 0xfc, 0xf4, 0x39, 0xa4, 0xdd, 0x67, 0x14, 0x0d, 0x21, 0x9a, 0xbd, 0x7a,
	0x33, 0x79, 0x0f, 0x01, 0x0c, 0x5e, 0xce, 0x5f, 0x5e, 0xe1, 0x5f, 0x27, 0x3d, 0x94, 0x40, 0x7c,
	0x71, 0x79, 0xfd, 0xe3, 0xa4, 0x6f, 0x4e, 0x6f, 0xbf, 0x9f, 0xcf, 0x27, 0xd1, 0x8b, 0xe9, 0x6f,
	0x9f, 0x57, 0xb5, 0xba, 0xd5, 0x37, 0xa7, 0x05, 0x67, 0x67, 0x6b, 0xdd, 0x52, 0x51, 0xdc, 0x92,
	0xba, 0xf1, 0x47, 0x2e, 0xe8, 0x99, 0xbb, 0xdf, 0x37, 0xee, 0x0f, 0xe6, 0xd9, 0xff, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x95, 0xaa, 0x5a, 0x12, 0x79, 0x06, 0x00, 0x00,
}
