// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type XuperMessage_MessageType int32

const (
	XuperMessage_SENDBLOCK                XuperMessage_MessageType = 0
	XuperMessage_POSTTX                   XuperMessage_MessageType = 1
	XuperMessage_BATCHPOSTTX              XuperMessage_MessageType = 2
	XuperMessage_GET_BLOCK                XuperMessage_MessageType = 3
	XuperMessage_PING                     XuperMessage_MessageType = 4
	XuperMessage_GET_BLOCKCHAINSTATUS     XuperMessage_MessageType = 5
	XuperMessage_GET_BLOCK_RES            XuperMessage_MessageType = 6
	XuperMessage_GET_BLOCKCHAINSTATUS_RES XuperMessage_MessageType = 7
	// 向邻近确认区块是否为最新状态区块
	XuperMessage_CONFIRM_BLOCKCHAINSTATUS     XuperMessage_MessageType = 8
	XuperMessage_CONFIRM_BLOCKCHAINSTATUS_RES XuperMessage_MessageType = 9
	XuperMessage_MSG_TYPE_NONE                XuperMessage_MessageType = 10
	// query RPC port information
	XuperMessage_GET_RPC_PORT     XuperMessage_MessageType = 11
	XuperMessage_GET_RPC_PORT_RES XuperMessage_MessageType = 12
	// get authentication information
	XuperMessage_GET_AUTHENTICATION     XuperMessage_MessageType = 13
	XuperMessage_GET_AUTHENTICATION_RES XuperMessage_MessageType = 14
	// chained-bft NEW_VIEW message
	XuperMessage_CHAINED_BFT_NEW_VIEW_MSG XuperMessage_MessageType = 15
	// chained-bft NEW_PROPOSAL message
	XuperMessage_CHAINED_BFT_NEW_PROPOSAL_MSG XuperMessage_MessageType = 16
	// chained-bft vote message
	XuperMessage_CHAINED_BFT_VOTE_MSG XuperMessage_MessageType = 17
	// broadcast new block id to other node
	XuperMessage_NEW_BLOCKID XuperMessage_MessageType = 18
	// new node used to add to network automatic
	XuperMessage_NEW_NODE XuperMessage_MessageType = 19
	// 消息头同步对(GET_HASHES <-> HASHES),
	// 发送方通过GET_HASHES消息询问区间范围内的所有区块哈希信息,
	// 接受方发送HASHES信息, 该消息携带其所知的区间范围内的BlockId列表
	XuperMessage_GET_BLOCKIDS     XuperMessage_MessageType = 20
	XuperMessage_GET_BLOCKIDS_RES XuperMessage_MessageType = 21
	// 消息对(GET_BLOCKS <-> BLOCKS),
	// 发送方通过GET_BLOCKS消息询问BlockId列表内的所有对应区块信息,
	// 接受方发送BLOCKS信息, 该消息携带具体Block
	XuperMessage_GET_BLOCKS     XuperMessage_MessageType = 22
	XuperMessage_GET_BLOCKS_RES XuperMessage_MessageType = 23
)

var XuperMessage_MessageType_name = map[int32]string{
	0:  "SENDBLOCK",
	1:  "POSTTX",
	2:  "BATCHPOSTTX",
	3:  "GET_BLOCK",
	4:  "PING",
	5:  "GET_BLOCKCHAINSTATUS",
	6:  "GET_BLOCK_RES",
	7:  "GET_BLOCKCHAINSTATUS_RES",
	8:  "CONFIRM_BLOCKCHAINSTATUS",
	9:  "CONFIRM_BLOCKCHAINSTATUS_RES",
	10: "MSG_TYPE_NONE",
	11: "GET_RPC_PORT",
	12: "GET_RPC_PORT_RES",
	13: "GET_AUTHENTICATION",
	14: "GET_AUTHENTICATION_RES",
	15: "CHAINED_BFT_NEW_VIEW_MSG",
	16: "CHAINED_BFT_NEW_PROPOSAL_MSG",
	17: "CHAINED_BFT_VOTE_MSG",
	18: "NEW_BLOCKID",
	19: "NEW_NODE",
	20: "GET_BLOCKIDS",
	21: "GET_BLOCKIDS_RES",
	22: "GET_BLOCKS",
	23: "GET_BLOCKS_RES",
}

var XuperMessage_MessageType_value = map[string]int32{
	"SENDBLOCK":                    0,
	"POSTTX":                       1,
	"BATCHPOSTTX":                  2,
	"GET_BLOCK":                    3,
	"PING":                         4,
	"GET_BLOCKCHAINSTATUS":         5,
	"GET_BLOCK_RES":                6,
	"GET_BLOCKCHAINSTATUS_RES":     7,
	"CONFIRM_BLOCKCHAINSTATUS":     8,
	"CONFIRM_BLOCKCHAINSTATUS_RES": 9,
	"MSG_TYPE_NONE":                10,
	"GET_RPC_PORT":                 11,
	"GET_RPC_PORT_RES":             12,
	"GET_AUTHENTICATION":           13,
	"GET_AUTHENTICATION_RES":       14,
	"CHAINED_BFT_NEW_VIEW_MSG":     15,
	"CHAINED_BFT_NEW_PROPOSAL_MSG": 16,
	"CHAINED_BFT_VOTE_MSG":         17,
	"NEW_BLOCKID":                  18,
	"NEW_NODE":                     19,
	"GET_BLOCKIDS":                 20,
	"GET_BLOCKIDS_RES":             21,
	"GET_BLOCKS":                   22,
	"GET_BLOCKS_RES":               23,
}

func (x XuperMessage_MessageType) String() string {
	return proto.EnumName(XuperMessage_MessageType_name, int32(x))
}

func (XuperMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{0, 0}
}

type XuperMessage_ErrorType int32

const (
	// success
	XuperMessage_SUCCESS XuperMessage_ErrorType = 0
	XuperMessage_NONE    XuperMessage_ErrorType = 1
	// common error
	XuperMessage_UNKNOW_ERROR             XuperMessage_ErrorType = 2
	XuperMessage_CHECK_SUM_ERROR          XuperMessage_ErrorType = 3
	XuperMessage_UNMARSHAL_MSG_BODY_ERROR XuperMessage_ErrorType = 4
	XuperMessage_CONNECT_REFUSE           XuperMessage_ErrorType = 5
	// block error
	XuperMessage_GET_BLOCKCHAIN_ERROR           XuperMessage_ErrorType = 6
	XuperMessage_BLOCKCHAIN_NOTEXIST            XuperMessage_ErrorType = 7
	XuperMessage_GET_BLOCK_ERROR                XuperMessage_ErrorType = 8
	XuperMessage_CONFIRM_BLOCKCHAINSTATUS_ERROR XuperMessage_ErrorType = 9
	XuperMessage_GET_AUTHENTICATION_ERROR       XuperMessage_ErrorType = 10
	XuperMessage_GET_AUTHENTICATION_NOT_PASS    XuperMessage_ErrorType = 11
)

var XuperMessage_ErrorType_name = map[int32]string{
	0:  "SUCCESS",
	1:  "NONE",
	2:  "UNKNOW_ERROR",
	3:  "CHECK_SUM_ERROR",
	4:  "UNMARSHAL_MSG_BODY_ERROR",
	5:  "CONNECT_REFUSE",
	6:  "GET_BLOCKCHAIN_ERROR",
	7:  "BLOCKCHAIN_NOTEXIST",
	8:  "GET_BLOCK_ERROR",
	9:  "CONFIRM_BLOCKCHAINSTATUS_ERROR",
	10: "GET_AUTHENTICATION_ERROR",
	11: "GET_AUTHENTICATION_NOT_PASS",
}

var XuperMessage_ErrorType_value = map[string]int32{
	"SUCCESS":                        0,
	"NONE":                           1,
	"UNKNOW_ERROR":                   2,
	"CHECK_SUM_ERROR":                3,
	"UNMARSHAL_MSG_BODY_ERROR":       4,
	"CONNECT_REFUSE":                 5,
	"GET_BLOCKCHAIN_ERROR":           6,
	"BLOCKCHAIN_NOTEXIST":            7,
	"GET_BLOCK_ERROR":                8,
	"CONFIRM_BLOCKCHAINSTATUS_ERROR": 9,
	"GET_AUTHENTICATION_ERROR":       10,
	"GET_AUTHENTICATION_NOT_PASS":    11,
}

func (x XuperMessage_ErrorType) String() string {
	return proto.EnumName(XuperMessage_ErrorType_name, int32(x))
}

func (XuperMessage_ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{0, 1}
}

// XuperMessage is the message of Xuper p2p server
type XuperMessage struct {
	Header               *XuperMessage_MessageHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Data                 *XuperMessage_MessageData   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *XuperMessage) Reset()         { *m = XuperMessage{} }
func (m *XuperMessage) String() string { return proto.CompactTextString(m) }
func (*XuperMessage) ProtoMessage()    {}
func (*XuperMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{0}
}

func (m *XuperMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XuperMessage.Unmarshal(m, b)
}
func (m *XuperMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XuperMessage.Marshal(b, m, deterministic)
}
func (m *XuperMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XuperMessage.Merge(m, src)
}
func (m *XuperMessage) XXX_Size() int {
	return xxx_messageInfo_XuperMessage.Size(m)
}
func (m *XuperMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_XuperMessage.DiscardUnknown(m)
}

var xxx_messageInfo_XuperMessage proto.InternalMessageInfo

func (m *XuperMessage) GetHeader() *XuperMessage_MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *XuperMessage) GetData() *XuperMessage_MessageData {
	if m != nil {
		return m.Data
	}
	return nil
}

// MessageHeader is the message header of Xuper p2p server
type XuperMessage_MessageHeader struct {
	Version              string                   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Logid                string                   `protobuf:"bytes,2,opt,name=logid,proto3" json:"logid,omitempty"`
	From                 string                   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Bcname               string                   `protobuf:"bytes,4,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Type                 XuperMessage_MessageType `protobuf:"varint,5,opt,name=type,proto3,enum=protos.XuperMessage_MessageType" json:"type,omitempty"`
	DataCheckSum         uint32                   `protobuf:"varint,6,opt,name=dataCheckSum,proto3" json:"dataCheckSum,omitempty"`
	ErrorType            XuperMessage_ErrorType   `protobuf:"varint,7,opt,name=errorType,proto3,enum=protos.XuperMessage_ErrorType" json:"errorType,omitempty"`
	EnableCompress       bool                     `protobuf:"varint,8,opt,name=enableCompress,proto3" json:"enableCompress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *XuperMessage_MessageHeader) Reset()         { *m = XuperMessage_MessageHeader{} }
func (m *XuperMessage_MessageHeader) String() string { return proto.CompactTextString(m) }
func (*XuperMessage_MessageHeader) ProtoMessage()    {}
func (*XuperMessage_MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{0, 0}
}

func (m *XuperMessage_MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XuperMessage_MessageHeader.Unmarshal(m, b)
}
func (m *XuperMessage_MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XuperMessage_MessageHeader.Marshal(b, m, deterministic)
}
func (m *XuperMessage_MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XuperMessage_MessageHeader.Merge(m, src)
}
func (m *XuperMessage_MessageHeader) XXX_Size() int {
	return xxx_messageInfo_XuperMessage_MessageHeader.Size(m)
}
func (m *XuperMessage_MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_XuperMessage_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_XuperMessage_MessageHeader proto.InternalMessageInfo

func (m *XuperMessage_MessageHeader) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *XuperMessage_MessageHeader) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *XuperMessage_MessageHeader) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *XuperMessage_MessageHeader) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *XuperMessage_MessageHeader) GetType() XuperMessage_MessageType {
	if m != nil {
		return m.Type
	}
	return XuperMessage_SENDBLOCK
}

func (m *XuperMessage_MessageHeader) GetDataCheckSum() uint32 {
	if m != nil {
		return m.DataCheckSum
	}
	return 0
}

func (m *XuperMessage_MessageHeader) GetErrorType() XuperMessage_ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return XuperMessage_SUCCESS
}

func (m *XuperMessage_MessageHeader) GetEnableCompress() bool {
	if m != nil {
		return m.EnableCompress
	}
	return false
}

// MessageData is the message data of Xuper p2p server
type XuperMessage_MessageData struct {
	// msgInfo is the message infomation, use protobuf coding style
	MsgInfo              []byte   `protobuf:"bytes,3,opt,name=msgInfo,proto3" json:"msgInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XuperMessage_MessageData) Reset()         { *m = XuperMessage_MessageData{} }
func (m *XuperMessage_MessageData) String() string { return proto.CompactTextString(m) }
func (*XuperMessage_MessageData) ProtoMessage()    {}
func (*XuperMessage_MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{0, 1}
}

func (m *XuperMessage_MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XuperMessage_MessageData.Unmarshal(m, b)
}
func (m *XuperMessage_MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XuperMessage_MessageData.Marshal(b, m, deterministic)
}
func (m *XuperMessage_MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XuperMessage_MessageData.Merge(m, src)
}
func (m *XuperMessage_MessageData) XXX_Size() int {
	return xxx_messageInfo_XuperMessage_MessageData.Size(m)
}
func (m *XuperMessage_MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_XuperMessage_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_XuperMessage_MessageData proto.InternalMessageInfo

func (m *XuperMessage_MessageData) GetMsgInfo() []byte {
	if m != nil {
		return m.MsgInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.XuperMessage_MessageType", XuperMessage_MessageType_name, XuperMessage_MessageType_value)
	proto.RegisterEnum("protos.XuperMessage_ErrorType", XuperMessage_ErrorType_name, XuperMessage_ErrorType_value)
	proto.RegisterType((*XuperMessage)(nil), "protos.XuperMessage")
	proto.RegisterType((*XuperMessage_MessageHeader)(nil), "protos.XuperMessage.MessageHeader")
	proto.RegisterType((*XuperMessage_MessageData)(nil), "protos.XuperMessage.MessageData")
}

func init() { proto.RegisterFile("network.proto", fileDescriptor_8571034d60397816) }

var fileDescriptor_8571034d60397816 = []byte{
	// 720 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0x36, 0x65, 0x59, 0x8f, 0xd1, 0xc3, 0x9b, 0xb1, 0xea, 0x10, 0x6e, 0x90, 0x0a, 0x3a, 0xb4,
	0x3a, 0x19, 0x85, 0xdb, 0x53, 0xd1, 0x8b, 0x44, 0xad, 0x2d, 0xc2, 0xd1, 0x2e, 0xb1, 0xbb, 0x8a,
	0x9d, 0x13, 0x41, 0x5b, 0x1b, 0xd7, 0x48, 0x24, 0x12, 0xa4, 0x92, 0x22, 0x3f, 0xa3, 0x40, 0x7f,
	0x43, 0x2f, 0xfd, 0x93, 0xc1, 0x2e, 0x49, 0x59, 0xb1, 0x15, 0x9f, 0xa8, 0xf9, 0x1e, 0xf3, 0xe2,
	0x88, 0xd0, 0x59, 0xe9, 0xf5, 0xdf, 0x71, 0xfa, 0xe1, 0x34, 0x49, 0xe3, 0x75, 0x8c, 0x35, 0xfb,
	0xc8, 0x06, 0xff, 0x02, 0xb4, 0xaf, 0x3f, 0x25, 0x3a, 0x9d, 0xe9, 0x2c, 0x8b, 0xee, 0x34, 0xfe,
	0x01, 0xb5, 0xa9, 0x8e, 0x16, 0x3a, 0x75, 0x9d, 0xbe, 0x33, 0x6c, 0x9d, 0x0d, 0x72, 0x43, 0x76,
	0xba, 0xad, 0x3a, 0x2d, 0x9e, 0xb9, 0x52, 0x14, 0x0e, 0xfc, 0x1d, 0xaa, 0x93, 0x68, 0x1d, 0xb9,
	0x15, 0xeb, 0xec, 0x3f, 0xe7, 0x34, 0x3a, 0x61, 0xd5, 0x27, 0xff, 0x57, 0xa0, 0xf3, 0x4d, 0x3e,
	0x74, 0xa1, 0xfe, 0x59, 0xa7, 0xd9, 0x7d, 0xbc, 0xb2, 0x4d, 0x34, 0x45, 0x19, 0x62, 0x0f, 0x0e,
	0x3e, 0xc6, 0x77, 0xf7, 0x0b, 0x5b, 0xa2, 0x29, 0xf2, 0x00, 0x11, 0xaa, 0xef, 0xd3, 0x78, 0xe9,
	0xee, 0x5b, 0xd0, 0xfe, 0xc6, 0x63, 0xa8, 0xdd, 0xdc, 0xae, 0xa2, 0xa5, 0x76, 0xab, 0x16, 0x2d,
	0x22, 0xd3, 0xe3, 0xfa, 0x4b, 0xa2, 0xdd, 0x83, 0xbe, 0x33, 0xec, 0x3e, 0xdf, 0xa3, 0xfa, 0x92,
	0x68, 0x61, 0xd5, 0x38, 0x80, 0xf6, 0x22, 0x5a, 0x47, 0xde, 0x5f, 0xfa, 0xf6, 0x83, 0xfc, 0xb4,
	0x74, 0x6b, 0x7d, 0x67, 0xd8, 0x11, 0xdf, 0x60, 0xf8, 0x27, 0x34, 0x75, 0x9a, 0xc6, 0xa9, 0xb1,
	0xb9, 0x75, 0x9b, 0xfe, 0xf5, 0xce, 0xf4, 0xb4, 0x54, 0x89, 0x07, 0x03, 0xfe, 0x0c, 0x5d, 0xbd,
	0x8a, 0x6e, 0x3e, 0x6a, 0x2f, 0x5e, 0x26, 0xa9, 0xce, 0x32, 0xb7, 0xd1, 0x77, 0x86, 0x0d, 0xf1,
	0x08, 0x3d, 0xf9, 0x05, 0x5a, 0x5b, 0x2b, 0x34, 0xab, 0x5a, 0x66, 0x77, 0xfe, 0xea, 0x7d, 0x6c,
	0xa7, 0x6f, 0x8b, 0x32, 0x1c, 0xfc, 0x53, 0xdd, 0x28, 0x6d, 0x81, 0x0e, 0x34, 0x25, 0x65, 0x93,
	0xf1, 0x1b, 0xee, 0x5d, 0x92, 0x3d, 0x04, 0xa8, 0x05, 0x5c, 0x2a, 0x75, 0x4d, 0x1c, 0x3c, 0x84,
	0xd6, 0x78, 0xa4, 0xbc, 0x69, 0x01, 0x54, 0x8c, 0xf6, 0x82, 0xaa, 0x30, 0xd7, 0xee, 0x63, 0x03,
	0xaa, 0x81, 0xcf, 0x2e, 0x48, 0x15, 0x5d, 0xe8, 0x6d, 0x08, 0x6f, 0x3a, 0xf2, 0x99, 0x54, 0x23,
	0x35, 0x97, 0xe4, 0x00, 0x5f, 0x40, 0x67, 0xc3, 0x84, 0x82, 0x4a, 0x52, 0xc3, 0x57, 0xe0, 0xee,
	0x12, 0x5b, 0xb6, 0x6e, 0x58, 0x8f, 0xb3, 0x73, 0x5f, 0xcc, 0x9e, 0xa6, 0x6b, 0x60, 0x1f, 0x5e,
	0x7d, 0x8f, 0xb5, 0xfe, 0xa6, 0x29, 0x38, 0x93, 0x17, 0xa1, 0x7a, 0x17, 0xd0, 0x90, 0x71, 0x46,
	0x09, 0x20, 0x81, 0xb6, 0x29, 0x28, 0x02, 0x2f, 0x0c, 0xb8, 0x50, 0xa4, 0x85, 0x3d, 0x20, 0xdb,
	0x88, 0xb5, 0xb6, 0xf1, 0x18, 0xd0, 0xa0, 0xa3, 0xb9, 0x9a, 0x52, 0xa6, 0x7c, 0x6f, 0xa4, 0x7c,
	0xce, 0x48, 0x07, 0x4f, 0xe0, 0xf8, 0x29, 0x6e, 0x3d, 0x5d, 0xdb, 0xae, 0xe9, 0x81, 0x4e, 0xc2,
	0xf1, 0xb9, 0x0a, 0x19, 0xbd, 0x0a, 0xdf, 0xfa, 0xf4, 0x2a, 0x9c, 0xc9, 0x0b, 0x72, 0x68, 0xdb,
	0x7d, 0xc4, 0x06, 0x82, 0x07, 0x5c, 0x8e, 0xde, 0x58, 0x05, 0x31, 0x9b, 0xdb, 0x56, 0xbc, 0xe5,
	0x8a, 0x5a, 0xe6, 0x85, 0xd9, 0xbe, 0xd1, 0xdb, 0x31, 0xfd, 0x09, 0x41, 0x6c, 0x43, 0xc3, 0x00,
	0x8c, 0x4f, 0x28, 0x39, 0x2a, 0x87, 0x2a, 0x68, 0x49, 0x7a, 0xe5, 0x50, 0x25, 0x62, 0x1b, 0xfc,
	0x01, 0xbb, 0x00, 0x1b, 0x54, 0x92, 0x63, 0x44, 0xe8, 0x3e, 0xc4, 0x56, 0xf3, 0x72, 0xf0, 0x5f,
	0x05, 0x9a, 0x9b, 0xeb, 0xc3, 0x16, 0xd4, 0xe5, 0xdc, 0xf3, 0xa8, 0x94, 0x64, 0xcf, 0xbc, 0x63,
	0xbb, 0x45, 0xc7, 0x14, 0x9c, 0xb3, 0x4b, 0xc6, 0xaf, 0x42, 0x2a, 0x04, 0x17, 0xa4, 0x82, 0x47,
	0x70, 0xe8, 0x4d, 0xa9, 0x77, 0x19, 0xca, 0xf9, 0xac, 0x00, 0xf7, 0xcd, 0x42, 0xe6, 0x6c, 0x36,
	0x12, 0x72, 0x9a, 0xcf, 0x18, 0x8e, 0xf9, 0xe4, 0x5d, 0xc1, 0x56, 0x4d, 0x75, 0x8f, 0x33, 0x46,
	0x3d, 0xb3, 0xf3, 0xf3, 0xb9, 0xa4, 0xe4, 0xe0, 0xe9, 0xf1, 0x14, 0xea, 0x1a, 0xbe, 0x84, 0xa3,
	0x2d, 0x94, 0x71, 0x45, 0xaf, 0x7d, 0xa9, 0x48, 0xdd, 0x54, 0x7e, 0xb8, 0xaa, 0x5c, 0xdd, 0xc0,
	0x01, 0xbc, 0xfe, 0xee, 0x6d, 0xe4, 0x9a, 0x66, 0x79, 0x7b, 0x8f, 0x5e, 0x65, 0xce, 0x02, 0xfe,
	0x04, 0x3f, 0xee, 0x60, 0x19, 0x57, 0x61, 0x30, 0x92, 0x92, 0xb4, 0xce, 0x02, 0x80, 0xe4, 0x2c,
	0x91, 0x3a, 0xfd, 0x7c, 0x7f, 0xab, 0x71, 0x0c, 0x5d, 0xa9, 0x57, 0x8b, 0xe0, 0x2c, 0x29, 0xbf,
	0x92, 0xbd, 0x5d, 0x7f, 0xec, 0x93, 0x9d, 0xe8, 0x60, 0x6f, 0xe8, 0xfc, 0xea, 0xdc, 0xe4, 0x1f,
	0xdc, 0xdf, 0xbe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x85, 0x29, 0x4d, 0x88, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// P2PServiceClient is the client API for P2PService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type P2PServiceClient interface {
	SendP2PMessage(ctx context.Context, opts ...grpc.CallOption) (P2PService_SendP2PMessageClient, error)
}

type p2PServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PServiceClient(cc grpc.ClientConnInterface) P2PServiceClient {
	return &p2PServiceClient{cc}
}

func (c *p2PServiceClient) SendP2PMessage(ctx context.Context, opts ...grpc.CallOption) (P2PService_SendP2PMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_P2PService_serviceDesc.Streams[0], "/protos.p2pService/SendP2pMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &p2PServiceSendP2PMessageClient{stream}
	return x, nil
}

type P2PService_SendP2PMessageClient interface {
	Send(*XuperMessage) error
	Recv() (*XuperMessage, error)
	grpc.ClientStream
}

type p2PServiceSendP2PMessageClient struct {
	grpc.ClientStream
}

func (x *p2PServiceSendP2PMessageClient) Send(m *XuperMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *p2PServiceSendP2PMessageClient) Recv() (*XuperMessage, error) {
	m := new(XuperMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// P2PServiceServer is the server API for P2PService service.
type P2PServiceServer interface {
	SendP2PMessage(P2PService_SendP2PMessageServer) error
}

// UnimplementedP2PServiceServer can be embedded to have forward compatible implementations.
type UnimplementedP2PServiceServer struct {
}

func (*UnimplementedP2PServiceServer) SendP2PMessage(srv P2PService_SendP2PMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendP2PMessage not implemented")
}

func RegisterP2PServiceServer(s *grpc.Server, srv P2PServiceServer) {
	s.RegisterService(&_P2PService_serviceDesc, srv)
}

func _P2PService_SendP2PMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(P2PServiceServer).SendP2PMessage(&p2PServiceSendP2PMessageServer{stream})
}

type P2PService_SendP2PMessageServer interface {
	Send(*XuperMessage) error
	Recv() (*XuperMessage, error)
	grpc.ServerStream
}

type p2PServiceSendP2PMessageServer struct {
	grpc.ServerStream
}

func (x *p2PServiceSendP2PMessageServer) Send(m *XuperMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *p2PServiceSendP2PMessageServer) Recv() (*XuperMessage, error) {
	m := new(XuperMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _P2PService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.p2pService",
	HandlerType: (*P2PServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendP2pMessage",
			Handler:       _P2PService_SendP2PMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "network.proto",
}
