// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/proposal.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProposalStatus int32

const (
	ProposalStatus_VOTING   ProposalStatus = 0
	ProposalStatus_SUCCESS  ProposalStatus = 1
	ProposalStatus_FAILURE  ProposalStatus = 2
	ProposalStatus_CANCELED ProposalStatus = 3
)

var ProposalStatus_name = map[int32]string{
	0: "VOTING",
	1: "SUCCESS",
	2: "FAILURE",
	3: "CANCELED",
}

var ProposalStatus_value = map[string]int32{
	"VOTING":   0,
	"SUCCESS":  1,
	"FAILURE":  2,
	"CANCELED": 3,
}

func (x ProposalStatus) String() string {
	return proto.EnumName(ProposalStatus_name, int32(x))
}

func (ProposalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{0}
}

// GovernTokenBalance
type GovernTokenBalance struct {
	TotalBalance                string   `protobuf:"bytes,1,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	AvailableBalanceForTdpos    string   `protobuf:"bytes,2,opt,name=available_balance_for_tdpos,json=availableBalanceForTdpos,proto3" json:"available_balance_for_tdpos,omitempty"`
	LockedBalanceForTdpos       string   `protobuf:"bytes,3,opt,name=locked_balance_for_tdpos,json=lockedBalanceForTdpos,proto3" json:"locked_balance_for_tdpos,omitempty"`
	AvailableBalanceForProposal string   `protobuf:"bytes,4,opt,name=available_balance_for_proposal,json=availableBalanceForProposal,proto3" json:"available_balance_for_proposal,omitempty"`
	LockedBalanceForProposal    string   `protobuf:"bytes,5,opt,name=locked_balance_for_proposal,json=lockedBalanceForProposal,proto3" json:"locked_balance_for_proposal,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *GovernTokenBalance) Reset()         { *m = GovernTokenBalance{} }
func (m *GovernTokenBalance) String() string { return proto.CompactTextString(m) }
func (*GovernTokenBalance) ProtoMessage()    {}
func (*GovernTokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{0}
}

func (m *GovernTokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GovernTokenBalance.Unmarshal(m, b)
}
func (m *GovernTokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GovernTokenBalance.Marshal(b, m, deterministic)
}
func (m *GovernTokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GovernTokenBalance.Merge(m, src)
}
func (m *GovernTokenBalance) XXX_Size() int {
	return xxx_messageInfo_GovernTokenBalance.Size(m)
}
func (m *GovernTokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GovernTokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GovernTokenBalance proto.InternalMessageInfo

func (m *GovernTokenBalance) GetTotalBalance() string {
	if m != nil {
		return m.TotalBalance
	}
	return ""
}

func (m *GovernTokenBalance) GetAvailableBalanceForTdpos() string {
	if m != nil {
		return m.AvailableBalanceForTdpos
	}
	return ""
}

func (m *GovernTokenBalance) GetLockedBalanceForTdpos() string {
	if m != nil {
		return m.LockedBalanceForTdpos
	}
	return ""
}

func (m *GovernTokenBalance) GetAvailableBalanceForProposal() string {
	if m != nil {
		return m.AvailableBalanceForProposal
	}
	return ""
}

func (m *GovernTokenBalance) GetLockedBalanceForProposal() string {
	if m != nil {
		return m.LockedBalanceForProposal
	}
	return ""
}

// TriggerDesc
type TriggerDesc struct {
	Height               int64             `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Module               int64             `protobuf:"varint,2,opt,name=module,proto3" json:"module,omitempty"`
	Method               string            `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Args                 map[string][]byte `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TriggerDesc) Reset()         { *m = TriggerDesc{} }
func (m *TriggerDesc) String() string { return proto.CompactTextString(m) }
func (*TriggerDesc) ProtoMessage()    {}
func (*TriggerDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{1}
}

func (m *TriggerDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerDesc.Unmarshal(m, b)
}
func (m *TriggerDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerDesc.Marshal(b, m, deterministic)
}
func (m *TriggerDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerDesc.Merge(m, src)
}
func (m *TriggerDesc) XXX_Size() int {
	return xxx_messageInfo_TriggerDesc.Size(m)
}
func (m *TriggerDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerDesc.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerDesc proto.InternalMessageInfo

func (m *TriggerDesc) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TriggerDesc) GetModule() int64 {
	if m != nil {
		return m.Module
	}
	return 0
}

func (m *TriggerDesc) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TriggerDesc) GetArgs() map[string][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

// Proposal
type Proposal struct {
	Module               string            `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Method               string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Args                 map[string][]byte `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Trigger              *TriggerDesc      `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"`
	VoteAmount           string            `protobuf:"bytes,5,opt,name=vote_amount,json=voteAmount,proto3" json:"vote_amount,omitempty"`
	Status               ProposalStatus    `protobuf:"varint,6,opt,name=status,proto3,enum=protos.ProposalStatus" json:"status,omitempty"`
	Proposer             string            `protobuf:"bytes,7,opt,name=proposer,proto3" json:"proposer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{2}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *Proposal) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Proposal) GetArgs() map[string][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Proposal) GetTrigger() *TriggerDesc {
	if m != nil {
		return m.Trigger
	}
	return nil
}

func (m *Proposal) GetVoteAmount() string {
	if m != nil {
		return m.VoteAmount
	}
	return ""
}

func (m *Proposal) GetStatus() ProposalStatus {
	if m != nil {
		return m.Status
	}
	return ProposalStatus_VOTING
}

func (m *Proposal) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func init() {
	proto.RegisterEnum("protos.ProposalStatus", ProposalStatus_name, ProposalStatus_value)
	proto.RegisterType((*GovernTokenBalance)(nil), "protos.GovernTokenBalance")
	proto.RegisterType((*TriggerDesc)(nil), "protos.TriggerDesc")
	proto.RegisterMapType((map[string][]byte)(nil), "protos.TriggerDesc.ArgsEntry")
	proto.RegisterType((*Proposal)(nil), "protos.Proposal")
	proto.RegisterMapType((map[string][]byte)(nil), "protos.Proposal.ArgsEntry")
}

func init() { proto.RegisterFile("protos/proposal.proto", fileDescriptor_98cf7ef12ed80c79) }

var fileDescriptor_98cf7ef12ed80c79 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x41, 0x6b, 0xdb, 0x4c,
	0x10, 0xfd, 0x24, 0x39, 0xb6, 0x33, 0xf2, 0x17, 0xc4, 0xb6, 0x09, 0xc2, 0xa1, 0xad, 0x71, 0xa1,
	0x98, 0x42, 0x65, 0xea, 0x1e, 0x52, 0x0a, 0x3d, 0x38, 0xb2, 0x12, 0x02, 0x21, 0x2d, 0xb2, 0xd3,
	0x43, 0x2f, 0x66, 0x2d, 0x6f, 0x25, 0x61, 0x59, 0x2b, 0x56, 0x2b, 0xd3, 0xfc, 0xb0, 0x9e, 0x4b,
	0xff, 0x59, 0xd1, 0xee, 0x4a, 0x6d, 0x84, 0x4e, 0xbd, 0xe9, 0xbd, 0x7d, 0x6f, 0xe6, 0xcd, 0x0c,
	0x82, 0xd3, 0x8c, 0x51, 0x4e, 0xf3, 0x69, 0xc6, 0x68, 0x46, 0x73, 0x9c, 0x38, 0x02, 0xa3, 0xae,
	0xa4, 0xc7, 0x3f, 0x74, 0x40, 0xd7, 0xf4, 0x40, 0x58, 0xba, 0xa2, 0x3b, 0x92, 0x5e, 0xe2, 0x04,
	0xa7, 0x01, 0x41, 0x2f, 0xe1, 0x7f, 0x4e, 0x39, 0x4e, 0xd6, 0x1b, 0x49, 0xd8, 0xda, 0x48, 0x9b,
	0x1c, 0xfb, 0x03, 0x41, 0x56, 0xa2, 0x8f, 0x70, 0x8e, 0x0f, 0x38, 0x4e, 0xf0, 0x26, 0x21, 0x95,
	0x70, 0xfd, 0x8d, 0xb2, 0x35, 0xdf, 0x66, 0x34, 0xb7, 0x75, 0x61, 0xb1, 0x6b, 0x89, 0xb2, 0x5d,
	0x51, 0xb6, 0x2a, 0xdf, 0xd1, 0x05, 0xd8, 0x09, 0x0d, 0x76, 0x64, 0xdb, 0xe2, 0x35, 0x84, 0xf7,
	0x54, 0xbe, 0x37, 0x8d, 0x2e, 0x3c, 0x6f, 0xef, 0x5b, 0xcd, 0x68, 0x77, 0x84, 0xfd, 0xbc, 0xa5,
	0xf5, 0x67, 0x25, 0x29, 0xc3, 0xb7, 0x74, 0xaf, 0x2b, 0x1c, 0xc9, 0xf0, 0xcd, 0x00, 0x95, 0x7d,
	0xfc, 0x4b, 0x03, 0x73, 0xc5, 0xe2, 0x30, 0x24, 0x6c, 0x41, 0xf2, 0x00, 0x9d, 0x41, 0x37, 0x22,
	0x71, 0x18, 0x71, 0xb1, 0x29, 0xc3, 0x57, 0xa8, 0xe4, 0xf7, 0x74, 0x5b, 0x24, 0x44, 0xac, 0xc3,
	0xf0, 0x15, 0x12, 0x3c, 0xe1, 0x11, 0xdd, 0xaa, 0x51, 0x15, 0x42, 0x6f, 0xa1, 0x83, 0x59, 0x98,
	0xdb, 0x9d, 0x91, 0x31, 0x31, 0x67, 0xcf, 0xe4, 0xb5, 0x72, 0xe7, 0xaf, 0x56, 0xce, 0x9c, 0x85,
	0xb9, 0x97, 0x72, 0xf6, 0xe0, 0x0b, 0xe9, 0xf0, 0x02, 0x8e, 0x6b, 0x0a, 0x59, 0x60, 0xec, 0xc8,
	0x83, 0x3a, 0x57, 0xf9, 0x89, 0x9e, 0xc2, 0xd1, 0x01, 0x27, 0x85, 0x0c, 0x30, 0xf0, 0x25, 0xf8,
	0xa0, 0xbf, 0xd7, 0xc6, 0x3f, 0x75, 0xe8, 0xd7, 0xfb, 0xf8, 0x13, 0x54, 0x53, 0x81, 0x9a, 0x41,
	0xf5, 0x47, 0x41, 0x1d, 0x15, 0xd4, 0x10, 0x41, 0x87, 0x55, 0xd0, 0xaa, 0x5e, 0x33, 0x25, 0x7a,
	0x03, 0x3d, 0x2e, 0x87, 0x10, 0xd7, 0x31, 0x67, 0x4f, 0x5a, 0x66, 0xf3, 0x2b, 0x0d, 0x7a, 0x01,
	0xe6, 0x81, 0x72, 0xb2, 0xc6, 0x7b, 0x5a, 0xa4, 0x5c, 0x9d, 0x03, 0x4a, 0x6a, 0x2e, 0x18, 0xe4,
	0x40, 0x37, 0xe7, 0x98, 0x17, 0xb9, 0xdd, 0x1d, 0x69, 0x93, 0x93, 0xd9, 0x59, 0x33, 0xc1, 0x52,
	0xbc, 0xfa, 0x4a, 0x85, 0x86, 0xd0, 0x97, 0xc7, 0x25, 0xcc, 0xee, 0x89, 0x6a, 0x35, 0xfe, 0xe7,
	0x0d, 0xbe, 0x5e, 0xc0, 0xc9, 0xe3, 0x76, 0x08, 0xa0, 0xfb, 0xe5, 0xd3, 0xea, 0xe6, 0xee, 0xda,
	0xfa, 0x0f, 0x99, 0xd0, 0x5b, 0xde, 0xbb, 0xae, 0xb7, 0x5c, 0x5a, 0x5a, 0x09, 0xae, 0xe6, 0x37,
	0xb7, 0xf7, 0xbe, 0x67, 0xe9, 0x68, 0x00, 0x7d, 0x77, 0x7e, 0xe7, 0x7a, 0xb7, 0xde, 0xc2, 0x32,
	0x2e, 0x27, 0x5f, 0x5f, 0x85, 0x31, 0x8f, 0x8a, 0x8d, 0x13, 0xd0, 0xfd, 0xf4, 0x7b, 0x91, 0x11,
	0x16, 0x44, 0x38, 0x4e, 0xd5, 0x27, 0x65, 0x64, 0x2a, 0x67, 0xdb, 0xc8, 0xbf, 0xf6, 0xdd, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x8f, 0x9d, 0x2c, 0xd5, 0x03, 0x00, 0x00,
}
