// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.2
// source: chainedBFTMsg.proto

package chainedBftPb

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// QuorumCertSign 是一个(Addr, Pk, 签名)三元组
type QuorumCertSign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	PublicKey string `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Sign      []byte `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *QuorumCertSign) Reset() {
	*x = QuorumCertSign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainedBFTMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuorumCertSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCertSign) ProtoMessage() {}

func (x *QuorumCertSign) ProtoReflect() protoreflect.Message {
	mi := &file_chainedBFTMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCertSign.ProtoReflect.Descriptor instead.
func (*QuorumCertSign) Descriptor() ([]byte, []int) {
	return file_chainedBFTMsg_proto_rawDescGZIP(), []int{0}
}

func (x *QuorumCertSign) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *QuorumCertSign) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *QuorumCertSign) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

// ProposalMsg 是chained-bft中定义的Block形式，区别在于其有一个parentQC，该存储只供chained-bft类使用
// ProposalMsg的结构就类似一个Block的结构
type ProposalMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 生产高度
	ProposalView int64  `protobuf:"varint,1,opt,name=proposalView,proto3" json:"proposalView,omitempty"`
	ProposalId   []byte `protobuf:"bytes,2,opt,name=proposalId,proto3" json:"proposalId,omitempty"`
	// 生产时间
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 上一个区块基本信息
	JustifyQC []byte `protobuf:"bytes,4,opt,name=JustifyQC,proto3" json:"JustifyQC,omitempty"`
	// 签名
	Sign *QuorumCertSign `protobuf:"bytes,5,opt,name=Sign,proto3" json:"Sign,omitempty"`
	// 消息摘要
	MsgDigest []byte `protobuf:"bytes,6,opt,name=MsgDigest,proto3" json:"MsgDigest,omitempty"`
}

func (x *ProposalMsg) Reset() {
	*x = ProposalMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainedBFTMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalMsg) ProtoMessage() {}

func (x *ProposalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chainedBFTMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalMsg.ProtoReflect.Descriptor instead.
func (*ProposalMsg) Descriptor() ([]byte, []int) {
	return file_chainedBFTMsg_proto_rawDescGZIP(), []int{1}
}

func (x *ProposalMsg) GetProposalView() int64 {
	if x != nil {
		return x.ProposalView
	}
	return 0
}

func (x *ProposalMsg) GetProposalId() []byte {
	if x != nil {
		return x.ProposalId
	}
	return nil
}

func (x *ProposalMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProposalMsg) GetJustifyQC() []byte {
	if x != nil {
		return x.JustifyQC
	}
	return nil
}

func (x *ProposalMsg) GetSign() *QuorumCertSign {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *ProposalMsg) GetMsgDigest() []byte {
	if x != nil {
		return x.MsgDigest
	}
	return nil
}

// VoteMsg is the vote message of the protocal.
type VoteMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoteInfo         []byte            `protobuf:"bytes,1,opt,name=VoteInfo,proto3" json:"VoteInfo,omitempty"`
	LedgerCommitInfo []byte            `protobuf:"bytes,2,opt,name=LedgerCommitInfo,proto3" json:"LedgerCommitInfo,omitempty"`
	Signature        []*QuorumCertSign `protobuf:"bytes,3,rep,name=Signature,proto3" json:"Signature,omitempty"`
}

func (x *VoteMsg) Reset() {
	*x = VoteMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainedBFTMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteMsg) ProtoMessage() {}

func (x *VoteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chainedBFTMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteMsg.ProtoReflect.Descriptor instead.
func (*VoteMsg) Descriptor() ([]byte, []int) {
	return file_chainedBFTMsg_proto_rawDescGZIP(), []int{2}
}

func (x *VoteMsg) GetVoteInfo() []byte {
	if x != nil {
		return x.VoteInfo
	}
	return nil
}

func (x *VoteMsg) GetLedgerCommitInfo() []byte {
	if x != nil {
		return x.LedgerCommitInfo
	}
	return nil
}

func (x *VoteMsg) GetSignature() []*QuorumCertSign {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_chainedBFTMsg_proto protoreflect.FileDescriptor

var file_chainedBFTMsg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x42, 0x46, 0x54, 0x4d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x42, 0x66,
	0x74, 0x50, 0x62, 0x22, 0x5c, 0x0a, 0x0e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67,
	0x6e, 0x22, 0xdd, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4d, 0x73,
	0x67, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x56, 0x69, 0x65,
	0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x56, 0x69, 0x65, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x4a, 0x75, 0x73, 0x74, 0x69, 0x66, 0x79, 0x51, 0x43,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x4a, 0x75, 0x73, 0x74, 0x69, 0x66, 0x79, 0x51,
	0x43, 0x12, 0x30, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x42, 0x66, 0x74, 0x50, 0x62, 0x2e, 0x51,
	0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x04, 0x53,
	0x69, 0x67, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x4d, 0x73, 0x67, 0x44, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x22, 0x8d, 0x01, 0x0a, 0x07, 0x56, 0x6f, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a,
	0x08, 0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x4c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x10, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3a, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x65, 0x64, 0x42, 0x66, 0x74, 0x50, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65,
	0x72, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x78, 0x75, 0x70, 0x65, 0x72, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x78, 0x75, 0x70, 0x65, 0x72,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x73,
	0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x42, 0x66, 0x74,
	0x50, 0x62, 0x3b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x42, 0x66, 0x74, 0x50, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chainedBFTMsg_proto_rawDescOnce sync.Once
	file_chainedBFTMsg_proto_rawDescData = file_chainedBFTMsg_proto_rawDesc
)

func file_chainedBFTMsg_proto_rawDescGZIP() []byte {
	file_chainedBFTMsg_proto_rawDescOnce.Do(func() {
		file_chainedBFTMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_chainedBFTMsg_proto_rawDescData)
	})
	return file_chainedBFTMsg_proto_rawDescData
}

var file_chainedBFTMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chainedBFTMsg_proto_goTypes = []interface{}{
	(*QuorumCertSign)(nil), // 0: chainedBftPb.QuorumCertSign
	(*ProposalMsg)(nil),    // 1: chainedBftPb.ProposalMsg
	(*VoteMsg)(nil),        // 2: chainedBftPb.VoteMsg
}
var file_chainedBFTMsg_proto_depIdxs = []int32{
	0, // 0: chainedBftPb.ProposalMsg.Sign:type_name -> chainedBftPb.QuorumCertSign
	0, // 1: chainedBftPb.VoteMsg.Signature:type_name -> chainedBftPb.QuorumCertSign
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chainedBFTMsg_proto_init() }
func file_chainedBFTMsg_proto_init() {
	if File_chainedBFTMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chainedBFTMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuorumCertSign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainedBFTMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainedBFTMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chainedBFTMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chainedBFTMsg_proto_goTypes,
		DependencyIndexes: file_chainedBFTMsg_proto_depIdxs,
		MessageInfos:      file_chainedBFTMsg_proto_msgTypes,
	}.Build()
	File_chainedBFTMsg_proto = out.File
	file_chainedBFTMsg_proto_rawDesc = nil
	file_chainedBFTMsg_proto_goTypes = nil
	file_chainedBFTMsg_proto_depIdxs = nil
}
