// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kernel/engines/xuperos/xpb/xpb.proto

package xpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"  //nolint:staticcheck
	xldgpb "github.com/xuperchain/xupercore/bcs/ledger/xledger/xldgpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transactions struct {
	Txs                  []*xldgpb.Transaction `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{0}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTxs() []*xldgpb.Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

type TxInfo struct {
	// 当前状态
	Status xldgpb.TransactionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=xldgpb.TransactionStatus" json:"status,omitempty"`
	// 离主干末端的距离（如果在主干上)
	Distance             int64               `protobuf:"varint,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Tx                   *xldgpb.Transaction `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TxInfo) Reset()         { *m = TxInfo{} }
func (m *TxInfo) String() string { return proto.CompactTextString(m) }
func (*TxInfo) ProtoMessage()    {}
func (*TxInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{1}
}

func (m *TxInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInfo.Unmarshal(m, b)
}
func (m *TxInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInfo.Marshal(b, m, deterministic)
}
func (m *TxInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInfo.Merge(m, src)
}
func (m *TxInfo) XXX_Size() int {
	return xxx_messageInfo_TxInfo.Size(m)
}
func (m *TxInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TxInfo proto.InternalMessageInfo

func (m *TxInfo) GetStatus() xldgpb.TransactionStatus {
	if m != nil {
		return m.Status
	}
	return xldgpb.TransactionStatus_TX_UNDEFINE
}

func (m *TxInfo) GetDistance() int64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *TxInfo) GetTx() *xldgpb.Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type BlockInfo struct {
	Status               xldgpb.BlockStatus    `protobuf:"varint,1,opt,name=status,proto3,enum=xldgpb.BlockStatus" json:"status,omitempty"`
	Block                *xldgpb.InternalBlock `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BlockInfo) Reset()         { *m = BlockInfo{} }
func (m *BlockInfo) String() string { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()    {}
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{2}
}

func (m *BlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfo.Unmarshal(m, b)
}
func (m *BlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfo.Marshal(b, m, deterministic)
}
func (m *BlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfo.Merge(m, src)
}
func (m *BlockInfo) XXX_Size() int {
	return xxx_messageInfo_BlockInfo.Size(m)
}
func (m *BlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfo proto.InternalMessageInfo

func (m *BlockInfo) GetStatus() xldgpb.BlockStatus {
	if m != nil {
		return m.Status
	}
	return xldgpb.BlockStatus_BLOCK_ERROR
}

func (m *BlockInfo) GetBlock() *xldgpb.InternalBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

type ChainStatus struct {
	LedgerMeta           *xldgpb.LedgerMeta    `protobuf:"bytes,1,opt,name=ledger_meta,json=ledgerMeta,proto3" json:"ledger_meta,omitempty"`
	UtxoMeta             *xldgpb.UtxoMeta      `protobuf:"bytes,2,opt,name=utxo_meta,json=utxoMeta,proto3" json:"utxo_meta,omitempty"`
	Block                *xldgpb.InternalBlock `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	BranchIds            []string              `protobuf:"bytes,4,rep,name=branch_ids,json=branchIds,proto3" json:"branch_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ChainStatus) Reset()         { *m = ChainStatus{} }
func (m *ChainStatus) String() string { return proto.CompactTextString(m) }
func (*ChainStatus) ProtoMessage()    {}
func (*ChainStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{3}
}

func (m *ChainStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainStatus.Unmarshal(m, b)
}
func (m *ChainStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainStatus.Marshal(b, m, deterministic)
}
func (m *ChainStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainStatus.Merge(m, src)
}
func (m *ChainStatus) XXX_Size() int {
	return xxx_messageInfo_ChainStatus.Size(m)
}
func (m *ChainStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ChainStatus proto.InternalMessageInfo

func (m *ChainStatus) GetLedgerMeta() *xldgpb.LedgerMeta {
	if m != nil {
		return m.LedgerMeta
	}
	return nil
}

func (m *ChainStatus) GetUtxoMeta() *xldgpb.UtxoMeta {
	if m != nil {
		return m.UtxoMeta
	}
	return nil
}

func (m *ChainStatus) GetBlock() *xldgpb.InternalBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *ChainStatus) GetBranchIds() []string {
	if m != nil {
		return m.BranchIds
	}
	return nil
}

type SystemStatus struct {
	ChainStatus          *ChainStatus `protobuf:"bytes,1,opt,name=chain_status,json=chainStatus,proto3" json:"chain_status,omitempty"`
	PeerUrls             []string     `protobuf:"bytes,2,rep,name=peer_urls,json=peerUrls,proto3" json:"peer_urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SystemStatus) Reset()         { *m = SystemStatus{} }
func (m *SystemStatus) String() string { return proto.CompactTextString(m) }
func (*SystemStatus) ProtoMessage()    {}
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{4}
}

func (m *SystemStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemStatus.Unmarshal(m, b)
}
func (m *SystemStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemStatus.Marshal(b, m, deterministic)
}
func (m *SystemStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemStatus.Merge(m, src)
}
func (m *SystemStatus) XXX_Size() int {
	return xxx_messageInfo_SystemStatus.Size(m)
}
func (m *SystemStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SystemStatus proto.InternalMessageInfo

func (m *SystemStatus) GetChainStatus() *ChainStatus {
	if m != nil {
		return m.ChainStatus
	}
	return nil
}

func (m *SystemStatus) GetPeerUrls() []string {
	if m != nil {
		return m.PeerUrls
	}
	return nil
}

type TipStatus struct {
	IsTrunkTip           bool     `protobuf:"varint,1,opt,name=is_trunk_tip,json=isTrunkTip,proto3" json:"is_trunk_tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TipStatus) Reset()         { *m = TipStatus{} }
func (m *TipStatus) String() string { return proto.CompactTextString(m) }
func (*TipStatus) ProtoMessage()    {}
func (*TipStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{5}
}

func (m *TipStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TipStatus.Unmarshal(m, b)
}
func (m *TipStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TipStatus.Marshal(b, m, deterministic)
}
func (m *TipStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TipStatus.Merge(m, src)
}
func (m *TipStatus) XXX_Size() int {
	return xxx_messageInfo_TipStatus.Size(m)
}
func (m *TipStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TipStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TipStatus proto.InternalMessageInfo

func (m *TipStatus) GetIsTrunkTip() bool {
	if m != nil {
		return m.IsTrunkTip
	}
	return false
}

type BlockID struct {
	Bcname  string `protobuf:"bytes,1,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Blockid []byte `protobuf:"bytes,2,opt,name=blockid,proto3" json:"blockid,omitempty"`
	// if need content
	NeedContent          bool     `protobuf:"varint,3,opt,name=need_content,json=needContent,proto3" json:"need_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockID) Reset()         { *m = BlockID{} }
func (m *BlockID) String() string { return proto.CompactTextString(m) }
func (*BlockID) ProtoMessage()    {}
func (*BlockID) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{6}
}

func (m *BlockID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockID.Unmarshal(m, b)
}
func (m *BlockID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockID.Marshal(b, m, deterministic)
}
func (m *BlockID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockID.Merge(m, src)
}
func (m *BlockID) XXX_Size() int {
	return xxx_messageInfo_BlockID.Size(m)
}
func (m *BlockID) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockID.DiscardUnknown(m)
}

var xxx_messageInfo_BlockID proto.InternalMessageInfo

func (m *BlockID) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *BlockID) GetBlockid() []byte {
	if m != nil {
		return m.Blockid
	}
	return nil
}

func (m *BlockID) GetNeedContent() bool {
	if m != nil {
		return m.NeedContent
	}
	return false
}

type ConsensusStatus struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ConsensusName        string   `protobuf:"bytes,2,opt,name=consensus_name,json=consensusName,proto3" json:"consensus_name,omitempty"`
	StartHeight          string   `protobuf:"bytes,3,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	ValidatorsInfo       string   `protobuf:"bytes,4,opt,name=validators_info,json=validatorsInfo,proto3" json:"validators_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsensusStatus) Reset()         { *m = ConsensusStatus{} }
func (m *ConsensusStatus) String() string { return proto.CompactTextString(m) }
func (*ConsensusStatus) ProtoMessage()    {}
func (*ConsensusStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{7}
}

func (m *ConsensusStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusStatus.Unmarshal(m, b)
}
func (m *ConsensusStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusStatus.Marshal(b, m, deterministic)
}
func (m *ConsensusStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusStatus.Merge(m, src)
}
func (m *ConsensusStatus) XXX_Size() int {
	return xxx_messageInfo_ConsensusStatus.Size(m)
}
func (m *ConsensusStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusStatus proto.InternalMessageInfo

func (m *ConsensusStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConsensusStatus) GetConsensusName() string {
	if m != nil {
		return m.ConsensusName
	}
	return ""
}

func (m *ConsensusStatus) GetStartHeight() string {
	if m != nil {
		return m.StartHeight
	}
	return ""
}

func (m *ConsensusStatus) GetValidatorsInfo() string {
	if m != nil {
		return m.ValidatorsInfo
	}
	return ""
}

type GetBlockHeaderRequest struct {
	Bcname               string   `protobuf:"bytes,1,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHeaderRequest) Reset()         { *m = GetBlockHeaderRequest{} }
func (m *GetBlockHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockHeaderRequest) ProtoMessage()    {}
func (*GetBlockHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{8}
}

func (m *GetBlockHeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHeaderRequest.Unmarshal(m, b)
}
func (m *GetBlockHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHeaderRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeaderRequest.Merge(m, src)
}
func (m *GetBlockHeaderRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockHeaderRequest.Size(m)
}
func (m *GetBlockHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeaderRequest proto.InternalMessageInfo

func (m *GetBlockHeaderRequest) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *GetBlockHeaderRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetBlockHeaderRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetBlockHeaderResponse struct {
	Blocks               []*xldgpb.InternalBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetBlockHeaderResponse) Reset()         { *m = GetBlockHeaderResponse{} }
func (m *GetBlockHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockHeaderResponse) ProtoMessage()    {}
func (*GetBlockHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{9}
}

func (m *GetBlockHeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHeaderResponse.Unmarshal(m, b)
}
func (m *GetBlockHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHeaderResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeaderResponse.Merge(m, src)
}
func (m *GetBlockHeaderResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockHeaderResponse.Size(m)
}
func (m *GetBlockHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeaderResponse proto.InternalMessageInfo

func (m *GetBlockHeaderResponse) GetBlocks() []*xldgpb.InternalBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type GetBlockTxsRequest struct {
	Bcname               string   `protobuf:"bytes,1,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Blockid              []byte   `protobuf:"bytes,2,opt,name=blockid,proto3" json:"blockid,omitempty"`
	Txs                  []int32  `protobuf:"varint,3,rep,packed,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockTxsRequest) Reset()         { *m = GetBlockTxsRequest{} }
func (m *GetBlockTxsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockTxsRequest) ProtoMessage()    {}
func (*GetBlockTxsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{10}
}

func (m *GetBlockTxsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockTxsRequest.Unmarshal(m, b)
}
func (m *GetBlockTxsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockTxsRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockTxsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockTxsRequest.Merge(m, src)
}
func (m *GetBlockTxsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockTxsRequest.Size(m)
}
func (m *GetBlockTxsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockTxsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockTxsRequest proto.InternalMessageInfo

func (m *GetBlockTxsRequest) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *GetBlockTxsRequest) GetBlockid() []byte {
	if m != nil {
		return m.Blockid
	}
	return nil
}

func (m *GetBlockTxsRequest) GetTxs() []int32 {
	if m != nil {
		return m.Txs
	}
	return nil
}

type GetBlockTxsResponse struct {
	Txs                  []*xldgpb.Transaction `protobuf:"bytes,4,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetBlockTxsResponse) Reset()         { *m = GetBlockTxsResponse{} }
func (m *GetBlockTxsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockTxsResponse) ProtoMessage()    {}
func (*GetBlockTxsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9685bde11a1952e, []int{11}
}

func (m *GetBlockTxsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockTxsResponse.Unmarshal(m, b)
}
func (m *GetBlockTxsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockTxsResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockTxsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockTxsResponse.Merge(m, src)
}
func (m *GetBlockTxsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockTxsResponse.Size(m)
}
func (m *GetBlockTxsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockTxsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockTxsResponse proto.InternalMessageInfo

func (m *GetBlockTxsResponse) GetTxs() []*xldgpb.Transaction {
	if m != nil {
		return m.Txs
	}
	return nil
}

func init() {
	proto.RegisterType((*Transactions)(nil), "protos.Transactions")
	proto.RegisterType((*TxInfo)(nil), "protos.TxInfo")
	proto.RegisterType((*BlockInfo)(nil), "protos.BlockInfo")
	proto.RegisterType((*ChainStatus)(nil), "protos.ChainStatus")
	proto.RegisterType((*SystemStatus)(nil), "protos.SystemStatus")
	proto.RegisterType((*TipStatus)(nil), "protos.TipStatus")
	proto.RegisterType((*BlockID)(nil), "protos.BlockID")
	proto.RegisterType((*ConsensusStatus)(nil), "protos.ConsensusStatus")
	proto.RegisterType((*GetBlockHeaderRequest)(nil), "protos.GetBlockHeaderRequest")
	proto.RegisterType((*GetBlockHeaderResponse)(nil), "protos.GetBlockHeaderResponse")
	proto.RegisterType((*GetBlockTxsRequest)(nil), "protos.GetBlockTxsRequest")
	proto.RegisterType((*GetBlockTxsResponse)(nil), "protos.GetBlockTxsResponse")
}

func init() {
	proto.RegisterFile("kernel/engines/xuperos/xpb/xpb.proto", fileDescriptor_e9685bde11a1952e)
}

var fileDescriptor_e9685bde11a1952e = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x51, 0x6b, 0xdb, 0x3a,
	0x14, 0x26, 0x71, 0x9a, 0xc6, 0xc7, 0xb9, 0x6d, 0x51, 0x69, 0xf1, 0xed, 0xe5, 0x42, 0xea, 0xad,
	0x2c, 0x50, 0x9a, 0xd0, 0x94, 0xed, 0x61, 0xf4, 0xa9, 0x1d, 0xb4, 0x85, 0x6d, 0x0f, 0x6e, 0x0a,
	0x63, 0x83, 0x19, 0xc5, 0x3e, 0x4d, 0x44, 0x1d, 0xc9, 0x93, 0xe4, 0xe2, 0x8d, 0xfd, 0x96, 0xfd,
	0x93, 0xfd, 0xb7, 0x61, 0xc9, 0x4e, 0xb3, 0xb2, 0xac, 0x0f, 0xc6, 0x3a, 0x47, 0xdf, 0xa7, 0xef,
	0x3b, 0xc7, 0xf2, 0x81, 0xe7, 0x77, 0x28, 0x39, 0xa6, 0x43, 0xe4, 0x53, 0xc6, 0x51, 0x0d, 0x8b,
	0x3c, 0x43, 0x29, 0xd4, 0xb0, 0xc8, 0x26, 0xe5, 0x33, 0xc8, 0xa4, 0xd0, 0x82, 0xb4, 0xcd, 0x4b,
	0xed, 0x1d, 0x9b, 0xed, 0x58, 0x48, 0x1c, 0x4e, 0x62, 0x35, 0x4c, 0x31, 0x99, 0xa2, 0x1c, 0x16,
	0x8b, 0x77, 0x32, 0x2d, 0x69, 0x36, 0xb4, 0xd4, 0xe0, 0x25, 0x74, 0xc7, 0x92, 0x72, 0x45, 0x63,
	0xcd, 0x04, 0x57, 0xe4, 0x00, 0x1c, 0x5d, 0x28, 0xbf, 0xd1, 0x73, 0xfa, 0xde, 0x68, 0x7b, 0x60,
	0x39, 0x83, 0x25, 0x48, 0x58, 0xee, 0x07, 0xdf, 0xa1, 0x3d, 0x2e, 0xae, 0xf8, 0xad, 0x20, 0xc7,
	0xd0, 0x56, 0x9a, 0xea, 0xbc, 0xe4, 0x34, 0xfa, 0x1b, 0xa3, 0x7f, 0xff, 0xc0, 0xb9, 0x36, 0x80,
	0xb0, 0x02, 0x92, 0x3d, 0xe8, 0x24, 0x4c, 0x69, 0xca, 0x63, 0xf4, 0x9b, 0xbd, 0x46, 0xdf, 0x09,
	0x17, 0x31, 0x79, 0x06, 0x4d, 0x5d, 0xf8, 0x4e, 0xaf, 0xb1, 0x4a, 0xbe, 0xa9, 0x8b, 0x00, 0xc1,
	0x3d, 0x4b, 0x45, 0x7c, 0x67, 0x0c, 0x1c, 0x3e, 0x32, 0xb0, 0x60, 0x19, 0xc8, 0x23, 0xe9, 0x43,
	0x58, 0x9b, 0x94, 0x69, 0xa3, 0xeb, 0x8d, 0x76, 0x6a, 0xec, 0x15, 0xd7, 0x28, 0x39, 0x4d, 0x0d,
	0x27, 0xb4, 0x98, 0xe0, 0x67, 0x03, 0xbc, 0xf3, 0x19, 0x65, 0x95, 0x7f, 0x72, 0x02, 0x9e, 0xed,
	0x5d, 0x34, 0x47, 0x4d, 0x8d, 0x9c, 0x37, 0x22, 0xf5, 0x11, 0x6f, 0xcd, 0xd6, 0x3b, 0xd4, 0x34,
	0x84, 0x74, 0xb1, 0x26, 0x47, 0xe0, 0xe6, 0xba, 0x10, 0x96, 0x62, 0x55, 0xb7, 0x6a, 0xca, 0x8d,
	0x2e, 0x84, 0x21, 0x74, 0xf2, 0x6a, 0xf5, 0x60, 0xd0, 0x79, 0xda, 0x20, 0xf9, 0x1f, 0x60, 0x22,
	0x29, 0x8f, 0x67, 0x11, 0x4b, 0x94, 0xdf, 0xea, 0x39, 0x7d, 0x37, 0x74, 0x6d, 0xe6, 0x2a, 0x51,
	0x41, 0x0c, 0xdd, 0xeb, 0xaf, 0x4a, 0xe3, 0xbc, 0xf2, 0xff, 0x0a, 0xba, 0x71, 0x59, 0x4e, 0xb4,
	0xd4, 0xaf, 0xb2, 0xcb, 0xf6, 0xf6, 0x0c, 0x96, 0x4a, 0x0d, 0xbd, 0x78, 0xa9, 0xee, 0xff, 0xc0,
	0xcd, 0x10, 0x65, 0x94, 0xcb, 0x54, 0xf9, 0x4d, 0xa3, 0xd2, 0x29, 0x13, 0x37, 0x32, 0x55, 0xc1,
	0x11, 0xb8, 0x63, 0x96, 0x55, 0xc8, 0x1e, 0x74, 0x99, 0x8a, 0xb4, 0xcc, 0xf9, 0x5d, 0xa4, 0x59,
	0x66, 0x14, 0x3a, 0x21, 0x30, 0x35, 0x2e, 0x53, 0x63, 0x96, 0x05, 0x9f, 0x61, 0xdd, 0x7e, 0xba,
	0x37, 0x64, 0x17, 0xda, 0x93, 0x98, 0xd3, 0x39, 0x1a, 0x98, 0x1b, 0x56, 0x11, 0xf1, 0x61, 0xdd,
	0x94, 0xc7, 0x12, 0xd3, 0xaf, 0x6e, 0x58, 0x87, 0x64, 0x1f, 0xba, 0x1c, 0x31, 0x89, 0x62, 0xc1,
	0x35, 0x72, 0x6d, 0x7a, 0xd4, 0x09, 0xbd, 0x32, 0x77, 0x6e, 0x53, 0xc1, 0x8f, 0x06, 0x6c, 0x9e,
	0x0b, 0xae, 0x90, 0xab, 0x5c, 0x55, 0xae, 0x7c, 0x58, 0xbf, 0x47, 0xa9, 0x98, 0xe0, 0x95, 0x52,
	0x1d, 0x92, 0x03, 0xd8, 0x88, 0x6b, 0x70, 0x64, 0xac, 0x34, 0x0d, 0xe0, 0x9f, 0x45, 0xf6, 0x7d,
	0xe9, 0x68, 0x1f, 0xba, 0x4a, 0x53, 0xa9, 0xa3, 0x19, 0xb2, 0xe9, 0xcc, 0xea, 0xba, 0xa1, 0x67,
	0x72, 0x97, 0x26, 0x45, 0x5e, 0xc0, 0xe6, 0x3d, 0x4d, 0x59, 0x42, 0xb5, 0x90, 0x2a, 0x62, 0xfc,
	0x56, 0xf8, 0x2d, 0x83, 0xda, 0x78, 0x48, 0x97, 0xd7, 0x35, 0xf8, 0x04, 0x3b, 0x17, 0xa8, 0x4d,
	0x0f, 0x2e, 0x91, 0x26, 0x28, 0x43, 0xfc, 0x92, 0xa3, 0xd2, 0x2b, 0xdb, 0xb1, 0x0b, 0xed, 0x4a,
	0xd6, 0xfe, 0x2b, 0x55, 0x44, 0x08, 0xb4, 0x14, 0xfb, 0x86, 0xc6, 0x8c, 0x13, 0x9a, 0x75, 0x70,
	0x01, 0xbb, 0x8f, 0x0f, 0x57, 0x59, 0x59, 0x0a, 0x39, 0x82, 0xb6, 0xe9, 0x62, 0xfd, 0x6b, 0xaf,
	0xb8, 0x58, 0x15, 0x28, 0xf8, 0x00, 0xa4, 0x3e, 0x68, 0x5c, 0xa8, 0xa7, 0x2c, 0xae, 0xfe, 0x62,
	0x5b, 0x76, 0x9c, 0x38, 0x3d, 0xa7, 0xbf, 0x66, 0x27, 0xc7, 0x29, 0x6c, 0xff, 0x76, 0x72, 0xe5,
	0xaf, 0x9a, 0x3b, 0xad, 0xbf, 0xcf, 0x9d, 0xb3, 0xd3, 0x8f, 0xaf, 0xa7, 0x4c, 0xcf, 0xf2, 0xc9,
	0x20, 0x16, 0x73, 0x3b, 0x0d, 0xcd, 0x4d, 0x1d, 0x3e, 0x4c, 0xbe, 0xd5, 0x13, 0x73, 0x62, 0xe7,
	0xe4, 0xc9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x60, 0xeb, 0x04, 0x56, 0x05, 0x00, 0x00,
}
